### ISSUE TITLE
oauth.getAuthorizationUrl is missing state and optional_scope parameter

### ISSUE THREAD

**Issue by tedgoddard** [HubSpot/hubspot-api-nodejs#1]
The call 

`hubspotClient.oauth.getAuthorizationUrl(config.clientId, redirectURI, scopes)`

does not include parameters for state or optional_scope. These parameters are supported by the server as documented here:

https://developers.hubspot.com/docs/methods/oauth2/initiate-oauth-integration

**Comment by AProts** [comment]
Fixed: 
@tedgoddard Thanks for catching that.
