### ISSUE TITLE
Duplicate parameter names for some API definitions

### ISSUE THREAD

**Issue by NewDark90** [HubSpot/hubspot-api-nodejs#117]
Some .d.ts files have duplicate parameter names.

The examples I've found exist in filesApi.d.ts,
`options` appears twice in `replace` and `upload`

https://unpkg.com/browse/@hubspot/api-client@5.0.0/lib/codegen/files/api/filesApi.d.ts

This may be a more systemic issue than just this file.

**Comment by NewDark90** [comment]
One further note. It seems as though this isn't just an issue with the definition. I think the javascript is equally affected where both parameters are named the same thing and thus the logic is probably wrong.

**Comment by ksvirkou-hubspot** [comment]
Hi @NewDark90 
 I ve fixed it in [the version 8.0.0 ](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.0)
