### ISSUE TITLE
TypeError: hubspotClient.crm.companies.associationsApi.createAssociation is not a function

### ISSUE THREAD

**Issue by SamSlate** [HubSpot/hubspot-api-nodejs#12]
>TypeError: hubspotClient.crm.companies.associationsApi.createAssociation is not a function

when running your demo code: 

    const hubspotClient = new hubspot.Client({ apiKey: process.env.API_KEY })
    const createContactResponse = await hubspotClient.crm.contacts.basicApi.create(contactObj)
    const createCompanyResponse = await hubspotClient.crm.companies.basicApi.create(companyObj)
    await hubspotClient.crm.companies.associationsApi.createAssociation(createCompanyResponse.body.id, 'contacts', createContactResponse.body.id)

**Comment by AProts** [comment]
Hi @SamSlate,

Thanks for catching this, we have a bug in the readme file. Since [v1.0.0-beta](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/v1.0.0-beta) we renamed "createAssociation" to "create". Readme will be updated in the upcoming release.

Kind Regards,
Andrii

**Comment by AProts** [comment]
fixed in 2.1.1
