### ISSUE TITLE
SLOW client.crm.contacts.getAll(1)

### ISSUE THREAD

**Issue by ohabash** [HubSpot/hubspot-api-nodejs#120]
I am using 

`this.client.crm.contacts.getAll(10)`

And it returns all contacts after 5 mins of waiting. 

I would like to pull just the 1st page of 10. Typescript shows `getAll` takes a limit so I put 10 there. but still all of them are returning.

Am i using it wrong?

**Comment by eblanchette** [comment]
Try using
```
const result: any = await hubspotClient.crm.contacts.basicApi.getPage(CONTACTS_LIMIT, after, propertyValues)
```

**Comment by ksvirkou-hubspot** [comment]
hey 
try to use 
```this.client.crm.contacts.getAll()``` or ```this.client.crm.contacts.getAll(100)```
