### ISSUE TITLE
BETWEEN operator not working in search

### ISSUE THREAD

**Issue by PraveenRanjan** [HubSpot/hubspot-api-nodejs#128]
I am using BETWEEN operator in search filter, I am passing "highValue" in filter group, but its throwing the following error: 

_"body": {
    "status": "error",
    **"message": "Invalid input JSON on line 1, column 102: Cannot construct instance of `com.hubspot.inbounddb.publicobject.core.v3.search.Filter`, problem: operator BETWEEN requires a highValue",**
    "correlationId": "02449535-b99a-41b6-8df5-fa37978dd691"
  },

**Sample Method for calling Search API**

app.get('/hubspot', async (req, res) => {
    const PublicObjectSearchRequest =     
        { filterGroups: [{"filters":[{"value":"1638264673941",  "highValue": "1640856673941", "propertyName":"closedate","operator":"BETWEEN"}]}], 
        sorts: ["DESCENDING"], properties: ["dealname"], limit: 10, after: 0 };

try {
  const apiResponse = await hubspotClient.crm.deals.searchApi.doSearch(PublicObjectSearchRequest);  
  console.log(JSON.stringify(apiResponse.body, null, 2));
//   console.log("apiResponse:: ",apiResponse.JSON());
} catch (e) {
  e.message === 'HTTP request failed'
    ? console.error(JSON.stringify(e.response, null, 2))
    : console.error(e)
}

});

**_SearchAPI with REST call works fine with BETWEEN operator._**

**Comment by karladler** [comment]
Are there any plans to fix this? Currently it's not even possible to pass the "highValue" param to the function since the types doesn't allow it.

**Comment by hunganhAtZehitomo** [comment]
Bump.
@karladler it works if in total you have less then 3 filters in a filterGroups. 

1 More issue related to this is the v3 client does not allow having filters array directly in request body. 
```
// Currently this does not work, it shows typescript error, and even if you ignore it, the client strips filters array away
hubspotClient.crm.contacts.searchApi.doSearch({filters: [], ...})
```

```
// the only way is to use filterGroups, but it is limited to having only 3 max filters
hubspotClient.crm.contacts.searchApi.doSearch({filterGroups: [
   filters: [...]
], ...})
```

**Comment by hunganhAtZehitomo** [comment]
Please, fix this issue as I need more than 3 filters in a filterGroups for my integration. Thanks!

**Comment by ksvirkou-hubspot** [comment]
> Please, fix this issue as I need more than 3 filters in a filterGroups for my integration. Thanks!

Unfortunately, We can't do it because it is limitation from API side.

**Comment by ksvirkou-hubspot** [comment]
> 

I'm working on it.

**Comment by dprose** [comment]
I'm having the same issue and would love to see a resolution soon. Looks like a fix has maybe just been implemented?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've just added `highValue` in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.0).

**Comment by dprose** [comment]
@ksvirkou-hubspot, thank you!
