### ISSUE TITLE
Any workarounds for 10,000 results API_LIMIT ? 

### ISSUE THREAD

**Issue by TommyCardello** [HubSpot/hubspot-api-nodejs#132]
Hi,

I'm using **crm.objects.doSearch** to search "meetings" object by date.

HubSpot API has a limitation. It will never return more than 10,000 results and I have way more than that.
I'm trying to find a way around this limitation. 

Was anyone successful in it?

My idea was to build an array of promises for each page (each page is limited to 100 results), then break down that array into chunks of 100.
For example, to get 35,000 meetings I would have 350 promises of 100 pages each. 
But to avoid hitting 10,000 limits I could run several separate API requests to get chunks of data with 10,000 each.

It doesn't work.

What I've noticed, if you try to get, for example, just 10 results "after": 10,000 API throws an error.
So, even splitting it into multiple requests doesn't work, because if you specify anything above 10,000 as "after" value, it won't work.

Any advice?
Thanks.

**Comment by Paul-Bird** [comment]
Hi Tommy, probably I don't understand the question, I am assuming you don't have more than 10,000 meetings a day, so could you search the meetings by a time interval small enough so the results would be within the 10,000 limit

**Comment by TommyCardello** [comment]
Hi @Paul-Bird,

Thanks. It was about 7 months ago, I don't remember all the details.
This was a project to build a tool to generate meeting-based reports for custom objects.

And my problem was that I couldn't pull more than 2-3 months of data, because I was hitting the limit of 10,000.
We needed year-over-year reports.

Since then, it became obvious that it makes more sense to get recent data from HubSpot on a daily basis, save it into my own database and generate reports based on that. Instead of pulling 10k+ meetings from Hubspot any time user changes the date range (which is extremely slow.)
