### ISSUE TITLE
Can't use `crm/schemas/api/coreApi.ts@create` because it doesn't have Oauth support

### ISSUE THREAD

**Issue by VesterDe** [HubSpot/hubspot-api-nodejs#133]
Hey there, I suspect this is a small bug in the code. We've got a use case where we first check if a custom object schema exists in HS, and if it doesn't, we create it.

The code to check if it's exists is [here](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/schemas/api/coreApi.ts#L413), and it works as expected. 

The code to create a custom object schema is [here](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/schemas/api/coreApi.ts#L262) and we're getting errors back consistently.

I rummaged around the codebase a bit and came to the conclusion that it's because the request is never populated with Oauth credentials, when they exist, which does happen for [getAll](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/schemas/api/coreApi.ts#L447-L449).

Adding those three lines of code fixes our problem.

I'd gladly make the PR, but your code is in a `codegen` folder, which makes me think my PR won't be the way to fix it?

**Comment by ksvirkou-hubspot** [comment]
hi @VesterDe 
API doesn’t support OAuth in this query  (crm/schemas/api/coreApi.ts@create)
and even if we do something in sdk it wouldn’t work

**Comment by VesterDe** [comment]
@ksvirkou-hubspot Thanks for the answer.

I believe the API does support Oauth, if the app has the permission specifically enabled, which ours does. I can easily make the call manually by appending the Bearer token to the headers for the create call.

We had to go through an internal process of yours to get the permission enabled. Does that mean you won't be adding it, since it's client specific?

**Comment by ksvirkou-hubspot** [comment]
is it work correctly with the Bearer token in headers ?

**Comment by VesterDe** [comment]
Here's a successful Post request made to a Hubspot Portal on behalf of our app, via Postman, with a Bearer token as auth:

![image](https://user-images.githubusercontent.com/722505/150959289-1fe0dd1d-41de-43da-b424-a2796ed73552.png)

**Comment by ksvirkou-hubspot** [comment]
I will try to clarify it 
Probably it is a bug in docs 
I ll write you as soon as possible

**Comment by ksvirkou-hubspot** [comment]
@VesterDe 
I ve added OAuth to schemas in the latest versions
