### ISSUE TITLE
Seach method doesnt sort when JSON.stringofy(sortObject)

### ISSUE THREAD

**Issue by BasherSG** [HubSpot/hubspot-api-nodejs#14]
Hi, i'm having this problem with the `doSearch()` method that doesn't sort at all if i send the sort array as `Array<string>`, but if i send it as `Array<object>` it sorts as expected, the thing is i'm quite sure this is because the internal request method does `JSON.stringify` over the whole body of the request before sending it so if i do `Array<string>` it will end with the `sorts` json being escaped.

This is a request body with `Array<string>` : 
`'{"sorts":["{\"propertyName\":\"lastmodifieddate\",\"direction\":\"DESCENDING\"}"]}'`

This is the one with `Array<object>` :
`'{"sorts":[{"propertyName":"lastmodifieddate","direction":"DESCENDING"}]'`

As you can see they are different but the thing is when programming on typescript the restriction enforces you to use `Array<string>` or to do `sorts as any`, but the restriction and the behavior doesn't really correspond to the documentation given.

**Comment by Hgoldberg15** [comment]
I can confirm that the `JSON.stringify ` is throwing off the sorting functionality. When I removed that piece it sorted correctly.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
We are fixing it in typescript.
Workable example for js:
```javascript
    const objectSearchRequest = {
        filterGroups: [
        {
            filters: [
            {
                propertyName: "createdate",
                operator: "GTE",
                value: "1615709177000",
            },
            ],
        },
        ],
        sorts: [
            {
                "propertyName": "lastmodifieddate",
                "direction": "DESCENDING"
            }
        ]
    };

    const response = await hubspotClient.crm.contacts.searchApi.doSearch(objectSearchRequest);
```

**Comment by ksvirkou-hubspot** [comment]
Workable example for ts:
```Typescript
const objectSearchRequest: PublicObjectSearchRequest = {
    filterGroups: [
      {
        filters: [
          {
            propertyName: "createdate",
            operator: "GTE",
            value: "1615709177000",
          },
        ],
      },
    ],
    sorts: ["-lastmodifieddate"],
    properties: ["email", "createdate", "lastmodifieddate"],
    limit: 100,
    after: 0,
  };

  const response = await hubspotClient.crm.contacts.searchApi.doSearch(objectSearchRequest);
```
The SDK version is 8.8.0.
Use sorts: ["-createdate"] to sort in desc and sorts: ["createdate"] in asc order.

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-api-nodejs/pull/391
