### ISSUE TITLE
TypeError: this.configuration.middleware is not iterable

### ISSUE THREAD

**Issue by ni9avenger** [HubSpot/hubspot-api-nodejs#143]
**HubSpot  API Client Error**
Node Version:  **16**
HubSpot Client Version: **6.0.0-beta**

Here is the screenshot of error
![image](https://user-images.githubusercontent.com/26461822/151604757-29f5570b-3ad9-4bc0-b214-0a96f8a4dd11.png)

**Comment by axelc-reworth** [comment]
this is a 6.0.0-beta version error, I was having the same issue but downgrading the SDK fixed it, I don't know how many of the features I am missing doing that but at least I can continue developing. I really hope they fix this ASAP

**Comment by ksvirkou-hubspot** [comment]
Hi 
could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/6.0.1-beta)?
 there are can be bugs because it is beta version
CC @ni9avenger @axelc-reworth

**Comment by axelc-reworth** [comment]
@ksvirkou-hubspot, the error is gone now, but the problem is that it now is returning a undefined when using get companies function.

**Comment by ksvirkou-hubspot** [comment]
I ve just checked and it works well
```javascript
require('dotenv').config({ path: '.env' })
const hubspot = require('@hubspot/api-client')
const hubspotClient = new hubspot.Client({ apiKey: process.env.HUBSPOT_API_KEY })

hubspotClient.crm.companies.basicApi.getPage().then((res) => {console.log(res)})
```
@axelc-reworth

**Comment by ni9avenger** [comment]
@ksvirkou-hubspot thanks.. issue is resolved...
