### ISSUE TITLE
where to find the hubspot api-client documentation?

### ISSUE THREAD

**Issue by terchris** [HubSpot/hubspot-api-nodejs#146]
I'm just about to start interacting with hubspot and I see that you have an api-client that I can use from node. 
I have tested the examples and I would prefer to use the api-client over using the rest api directly.

I can find some documentation on how to use the api-client by reading the examples in the readme.md and the code in sample-apps-list.
But there must be a place where you have the full documentation on the api-client.

**Comment by ksvirkou-hubspot** [comment]
Hi @terchris 
I can find documentation [here](https://developers.hubspot.com/docs/api/overview)

**Comment by kevincolten** [comment]
I believe @terchris was asking for documentation around this node package in particular. Is there any?

**Comment by kevincolten** [comment]
@ksvirkou-hubspot I've submitted a PR to automatically generate and publish documentation. https://github.com/HubSpot/hubspot-api-nodejs/pull/409

@terchris Is this the type of documentation you are looking for?
https://kevincolten.github.io/hubspot-api-nodejs/
