### ISSUE TITLE
INVALID_AUTHENTICATION when trying to list pipelines

### ISSUE THREAD

**Issue by nomoney4me** [HubSpot/hubspot-api-nodejs#148]
I am trying to list all pipelines for deals but it seems that I am getting the following error regardless of whether I am trying to access the `schemas.coreApi` or the `pipelinesApi`. In the screenshot, you can see that the .searchContacts() above it is working just fine so it is not a matter of invalid token.

Can anyone help troubleshoot this?

![image](https://user-images.githubusercontent.com/9965349/152181637-0c4faa5b-d3f2-4534-9551-94ecea1bc774.png)

```
{
  "status": "error",
  "message": "Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview",
  "correlationId": "cead9e40-5345-405d-aeea-edc6f13b8cb1",
  "category": "INVALID_AUTHENTICATION"
}
Headers: {
  "access-control-allow-credentials": "false",
  "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
  "cf-cache-status": "DYNAMIC",
  "cf-ray": "6d74583848baf186-PIT",
  "connection": "close",
  "content-length": "316",
  "content-type": "application/json;charset=utf-8",
  "date": "Wed, 02 Feb 2022 15:10:08 GMT",
  "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "nel": "{\"success_fraction\":0.01,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=kLD0criB9UX2R%2BPg2IbCtrqYbkNooXogMTiqz680a0ukG%2F7xqrdjNJnviZPn%2F0Pn5Trw2SKH7QJQdf1Kgsw4Y76saDhig3w2UNGof8q1EnNrLpi6g6khlQR4VQcT6fBB\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "server": "cloudflare",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
  "vary": "Accept-Encoding",
  "x-hubspot-correlation-id": "cead9e40-5345-405d-aeea-edc6f13b8cb1"
}
```

**Comment by ksvirkou-hubspot** [comment]
HI @nomoney4me 
What version SDK do you use?

**Comment by nomoney4me** [comment]
> HI @nomoney4me What version SDK do you use?

I am using "@hubspot/api-client": "^6.0.1-beta" in nodejs.

**Comment by ksvirkou-hubspot** [comment]
It is a bug of this version (it is not stable version)
I'll fix it as soon as possible 
You can use [5.0.0](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/5.0.0) 
@nomoney4me

**Comment by nomoney4me** [comment]
Gotcha, thank you. 5.0.0 seems to work okay but it looks like moving 5 -> 6 will be a big change since I have to rewrite a few of my pieces to get it working with 5.0.0.

**Comment by ksvirkou-hubspot** [comment]
you can wait 
I'm working on it right now

**Comment by nomoney4me** [comment]
> you can wait I'm working on it right now

No rush, I was just noting it for anyone planning on switching from 5 -> 6.
