### ISSUE TITLE
typescript errors with standard http & request node modules

### ISSUE THREAD

**Issue by roymap** [HubSpot/hubspot-api-nodejs#15]
When running the typescript compiler (tsc), I get the following two errors in a lot places:

**import http from 'http';**
> Module "http" has no default export

You do use `import http = require('http');` in another file, which is the proper way to import http.  Or you can use `import * as http from 'http'`

**import localVarRequest from 'request';**
> Module "request" can only be default-imported using the 'esModuleInterop' flag

**Comment by roymap** [comment]
Looks like I needed `"esModuleInterop": true` in the tsconfig.json

**Comment by iDVB** [comment]
I'm also having this issue and adding `"esModuleInterop": true` does not fix the issue.
Any other ideas?
