### ISSUE TITLE
Missing `apiRequest` function on 6.x

### ISSUE THREAD

**Issue by luissquall** [HubSpot/hubspot-api-nodejs#152]
Hello guys, 

`apiRequest` function is missing from v6.x. Is there any plan to remove it from this version, was it renamed to something else? Works great in v5.

Thanks!

**Comment by ksvirkou-hubspot** [comment]
Hi @luissquall 
I ll add it as soon as possible

**Comment by ksvirkou-hubspot** [comment]
Hi @luissquall 
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/6.0.1-beta3) please?
