### ISSUE TITLE
.serialize() cause undefined in filter

### ISSUE THREAD

**Issue by nomoney4me** [HubSpot/hubspot-api-nodejs#156]
It looks like when putting in a string[] into values, serialize is nullifying it somehow.
![image](https://user-images.githubusercontent.com/9965349/153619041-092474e8-9c22-4c3d-8c6b-fa405c154c4e.png)

I will dig further for more information but figured posting it here in case someone more proficient in .serialize() can help fix this so it can support "values" using IN and NOT_IN operators.

Note: running version 5.0.0.

Might be here: https://github.com/HubSpot/hubspot-api-nodejs/blob/0fe434385f8a15278da6c9ed239dcfc45137c5ec/codegen/crm/deals/apis/SearchApi.ts#L46

**Comment by ksvirkou-hubspot** [comment]
Hi
it is fixed
Could you check [the latest version of SDK](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0), please?
