### ISSUE TITLE
How to renew access token

### ISSUE THREAD

**Issue by pRatikSathaye** [HubSpot/hubspot-api-nodejs#160]
Hello,

I am using version `"@hubspot/api-client": "6.0.1-beta2"`

I am trying to find a way to renew access token using refresh_token as my access token is expired.
I tried using `accessTokensApi, refreshTokensApi and tokensApi`, but that did not help.

Seeing the README.md example, I tried using `apiRequest` method but getting `hubspotClient.apiRequest is not a function`

Can anybody please help?

**Comment by ksvirkou-hubspot** [comment]
Hi 
Could you check [this sapmle app](https://github.com/HubSpot/sample-apps-oauth) please?

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/sample-apps-oauth/blob/main/node/src/index.js#L62
```javascript
const result = await hubspotClient.oauth.tokensApi.createToken(
    GRANT_TYPES.REFRESH_TOKEN,
    undefined,
    undefined,
    CLIENT_ID,
    CLIENT_SECRET,
    tokenStore.refreshToken
  );
 
  hubspotClient.setAccessToken(result.accessToken);
```
