### ISSUE TITLE
TimelineEvent class requires id but comment recommends not to provide one

### ISSUE THREAD

**Issue by VelociRaphtor** [HubSpot/hubspot-api-nodejs#161]
API doesn't require `id` in `TimelineEvent` class and in fact, the comment recommends not providing one so the service generates one.

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-api-nodejs/pull/155

**Comment by ksvirkou-hubspot** [comment]
Hi @VelociRaphtor 
could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/6.0.1-beta4)?
