### ISSUE TITLE
Single-send API docs incorrect

### ISSUE THREAD

**Issue by Kncarrier** [HubSpot/hubspot-api-nodejs#168]
I was trying to add the single-send API to my application using the example code from the docs (found [here](https://developers.hubspot.com/docs/api/marketing/transactional-emails)). Below is the section from the example that shows the path for using this package's methods for the single-send API, but the path is wrong.

```
try {
  const apiResponse = await hubspotClient.marketing.transactional.singleEmail.send.singleSendApi.sendEmail(PublicSingleSendRequestEgg);
  console.log(JSON.stringify(apiResponse.body, null, 2));
} catch (e) {
  e.message === 'HTTP request failed'
    ? console.error(JSON.stringify(e.response, null, 2))
    : console.error(e)
}
```

Using this returns an error `TypeError: Cannot read property 'send' of undefined`. The correct path is `hubspotClient.marketing.transactional.singleSendApi.sendEmail`. I'm guessing this got moved without updating the docs.

**Comment by jon-armen** [comment]
+1 on this.  I suspect the docs should be updated roughly as follows:

`const apiResponse =
      await hubspotClient.marketing.transactional.singleSendApi.sendEmail(
        PublicSingleSendRequestEgg
      );
    console.log(JSON.stringify(apiResponse, null, 2));`

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
Thank you for reporting the issue 
I ve fixed the docks
