### ISSUE TITLE
Way to get Portal/Hub Id

### ISSUE THREAD

**Issue by pRatikSathaye** [HubSpot/hubspot-api-nodejs#170]
Hello,

I am able to use `OAuth2` flow and get access token, but I also need `portal/hub id` of customer who has installed my connected app.
Is there any way  through which I can get `portal/hub id` of customer account?

**Comment by sharpyfox** [comment]
Hub id is available in the getAccessToken response: https://github.com/HubSpot/hubspot-api-nodejs/blob/16529bb14387503ec18ef47d75b01262ba8910b4/codegen/oauth/types/PromiseAPI.ts#L27

**Comment by pRatikSathaye** [comment]
Thank you @sharpyfox ,
This works fine.

Is there any way to retrieve this `hubId` while calling `createToken`?

**Comment by sharpyfox** [comment]
At least I don't know if it's possible. We are using getAccessToken for the same purpose, it's 1 request per integration, so it's not that complicated or problematic.

**Comment by pRatikSathaye** [comment]
@sharpyfox ,
Maybe what you are suggesting feels right, but IMO, if we are connecting to a user account and getting the access token then we should also get Account related metadata instead of making an `extra` API call just to retrieve the hub id.
