### ISSUE TITLE
Error in Create a batch of associations - "_from" should be used instead of "from" in inputs

### ISSUE THREAD

**Issue by vishnukt** [HubSpot/hubspot-api-nodejs#171]
Error - Invalid input JSON on line 1, column 62: Cannot build PublicAssociation, some of required attributes are not set [from]

In hubspot "Create a batch of associations" documentation "from" is used.
"_from" should be used instead of "from" in inputs - this will solve error.

"_from" must me changed to "from" in the source code to solve this issue - 
node_modules/@hubspot/api-client/lib/codegen/crm/associations/models/PublicAssociation.d.ts

**Comment by eweiler-sfm** [comment]
Thank you @vishnukt this helped me today!

**Comment by vtk13** [comment]
Is there explanation for this update? I don't want to debug it again if '_from' is changed back to 'from'.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
We changed code generator and in new generator `from` is reserved word.
I've updated docs (changed `form` to `_from`) and  README.

**Comment by Systerr** [comment]
Just a feedback based on few hours debugging. 
Actually this is a breaking change, but no info in changelog about it at all.  Please add it here into.

We have upgraded from the old version where "from" works fine and on the last version. Api error is fully confusing  
"Body: {"status":"error","message":"Invalid input JSON on line 1, column 61. Some required fields were not set: [from]","correlationId":"xxx","category":"VALIDATION_ERROR"}"

And from docs really hard to understand what version as associations sdk used (v4 or v3)

**Comment by ksvirkou-hubspot** [comment]
> where

I've updated [CHANGELOG.md](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/CHANGELOG.md).
The SDK use the both versions. Very soon the SDK will fully migrate to v4.
