### ISSUE TITLE
When associating a company with a contact, it always marks the newly associated company as the user's new primary company.

### ISSUE THREAD

**Issue by daniel-rsi** [HubSpot/hubspot-api-nodejs#176]
This creates a challenge for my use-case.  A contact can be associated with multiple companies (i.e. as a consultant).  It makes sense for their first associated company to default to be their primary, but I don't want every new company they're associated with to be marked as their primary.  

As far as I can tell, the current programmatic interface does not allow for controlling this behavior.

```
const association: BatchInputPublicAssociation = {
  inputs: [
    {
      '_from': { id: contactId },
      'to': { id: companyId },
      'type': 'contact_to_company',
    }
  ]
};

this.client.crm.associations.batchApi.create('contact', 'company', association);
```

I would prefer if it only set the company as their primary if it's their first company association, or allow passing additional metadata that your API could understand, like a `markPrimary: boolean` flag or something in the association input.

**Comment by ksvirkou-hubspot** [comment]
Hi @daniel-rsi .
`contact_to_company` association type creates primary association. I don't know why(question to Hubspot).
I created enum `AssociationTypes` (`AssociationTypes.contactToCompany` is not primary) In the latest SDK version 8.5.0 .
Workable example
```javascript
    const BatchInputPublicAssociation = { 
        inputs: [
            {
                _from: {
                    id : '313465'
                },
                to: {
                    id: '9263529601'
                },
                type: AssociationTypes.contactToCompany
            }
        ] 
    };
    
    const response = await hubspotClient.crm.associations.batchApi.create(
        'contacts',
        'companies',
        BatchInputPublicAssociation
    );
```
In 8.4.2 or lower you can use `hubspotClient.crm.associations.typesApi.getAll('contacts','companies')`.
it returns all association's types and you can use not primary type.
Workable example
```javascript
    const BatchInputPublicAssociation = { 
        inputs: [
            {
                _from: {
                    id : '313465'
                },
                to: {
                    id: '9263529601'
                },
                type: '279'
            }
        ] 
    };
    const response = await hubspotClient.crm.associations.batchApi.create(
        'contacts',
        'companies',
        BatchInputPublicAssociation
    );
```
if you create the first contact company association, it will be primary in despite of association type.
