### ISSUE TITLE
updateContactByEmail cannot find idProperty location

### ISSUE THREAD

**Issue by shalev007** [HubSpot/hubspot-api-nodejs#182]
Hey,
I'm also looking for a way to update contact by email and I cannot find where to pass `idProperty`
I know there's a way because of this issue #99 

And I couldn't find a reference to that in the documentation

my code currently looks like this: `await this.hubspotSDK.crm.contacts.basicApi.update(id, { properties });`

**Comment by shalev007** [comment]
any updates?
@ksvirkou-hubspot

**Comment by myishay** [comment]
@ksvirkou-hubspot any news on that?

**Comment by dshukertjr** [comment]
@ksvirkou-hubspot it should be supported as it says [here](https://developers.hubspot.com/docs/api/crm/contacts) and I also tried it myself using the following curl command

```sh
curl --request PATCH \
   --url 'https://api.hubapi.com/crm/v3/objects/contacts/tyler%40supabase.io?hapikey=MY_API_KEY&idProperty=email' \
   --header 'content-type: application/json' \
   --data '{
   "properties": {
     "lastname": "NewLastname"
   }
 }'
```

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I ve added it to [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)
```javascript
const response = await hubspotClient.crm.contacts.basicApi.update('mike@mailforspam.com', {
        "properties": {
          "lastname": "NewLastname"
        }
      }, 'email')
```
