### ISSUE TITLE
getContactByEmail should expose idProperty

### ISSUE THREAD

**Issue by dreadjr** [HubSpot/hubspot-api-nodejs#183]
I would expect the contacts api to be able to get by email.
`hubspot.crm.contacts.basicApi.getById(email);`

But, from what I can see `idProperty` is not settable in the `getById`
```
const eventResponse = await hubspot.apiRequest({
      method: "GET",
      path: `/crm/v3/objects/contacts/${email}`,
      qs: { idProperty: "email", properties: [] },
    });
```

**Comment by rfrank-usgb** [comment]
bump, this would be super useful 👍

**Comment by ksvirkou-hubspot** [comment]
Currently it isn’t supposed by API

**Comment by softwaredeveloptam** [comment]
I believe you could still query by email via the `searchApi`. 
```js
const result = await hubspotClient.crm.contacts.searchApi.doSearch({
  query: "test@hubspot.com",
  limit: 100,
  properties: undefined,
  filterGroups: [],
  after: 0,
})
```
This works for getting the user test@hubspot.com.

**Comment by dreadjr** [comment]
Yes, there are many ways to get the result. The main motivation for some of the tickets is to align the API and the SDK. Options that are supported in the API should be exposed via the SDK in their corresponding methods.

An example would be 
```
hubspot.crm.contacts.basicApi.getById(email, { idProperty: "email", properties: [] });
OR
hubspot.crm.contacts.basicApi.getByEmail(email);
```
You can see from my original post this is supported by the API, just not the SDK.

I ended up writing my own library because of the inconsistencies I found.

**Comment by dshukertjr** [comment]
Supporting `idProperty` on the client side could be useful when updating a contact by email too. 

Currently using the API client, there is no way to update a contact in a single request. We would have to first get the contact ID via the search API and then update the contact by its contact ID via update endpoint. Exposing `idProperty` would allow us to perform this in single API call.

**Comment by rfrank-usgb** [comment]
@ksvirkou-hubspot see @dreadjr post above ^

**Comment by ksvirkou-hubspot** [comment]
for 5.0.0 
```javascript
const response = await hubspotClient.crm.contacts.basicApi.getById('mike@mailforspam.com', [], [], false, 'email');
console.log(response);
```
`https://api.hubapi.com/crm/v3/objects/contacts/mike%40mailforspam.com?archived=false&idProperty=email`
I will try to contact with API developers  one more time

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
I ve added it to [the latest version ](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
I ve added it to [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/7.0.0)

```javascript
const response = await hubspotClient.crm.contacts.basicApi.getById('mike@mailforspam.com', undefined, undefined, undefined, false, 'email')
```
