### ISSUE TITLE
How to generate the $identification_token_generation_request parameter in the conversations() module?

### ISSUE THREAD

**Issue by kylescousin** [HubSpot/hubspot-api-nodejs#188]

**Comment by willchris2** [comment]
I also have an issue with the token generation.
First of all in the documentation example the generateToken function is called like this:

`hubspotClient.conversations.visitorIdentification.tokens.create.generateApi.generateToken(IdentificationTokenGenerationRequest)`

However I can only call the Methode like this:

`hubspotClient.conversations.visitorIdentification.generateApi.generateToken(IdentificationTokenGenerationRequest)`

When I call the function with my accessToken of my private App i get the error message:
**Authentication credentials not found**
