### ISSUE TITLE
How do I add a note to a deal?

### ISSUE THREAD

**Issue by magician11** [HubSpot/hubspot-api-nodejs#19]
The closest i could find was using a normal POST request like https://legacydocs.hubspot.com/docs/methods/engagements/create_engagement

Can a note be added with this api-client?

**Comment by atanasiuk-hubspot** [comment]
Hi, @magician11. This SDK works with [new](https://developers.hubspot.com/docs/api/overview) HubSpot API.

[Engagements API](https://developers.hubspot.com/docs/api/crm/engagements) is under development now.

**Comment by lorenzojlamas** [comment]
Do they have an approximate date?

**Comment by xiaoyu-tamu** [comment]
The Engagements API is in preview now. Any updates

Please note: This API is currently in beta and is subject to change based on testing and feedback. By using these endpoints you agree to adhere to our Developer Terms& Developer Beta Terms. You also acknowledge and understand the risk associated with testing an unstable API. For the latest stable version of the engagements API, check out the legacy engagements overview.

**Comment by ksvirkou-hubspot** [comment]
HI Everyone 
The API was add in version [6.0.1-beta.6](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/6.0.1-beta.6)|
```javascript
hubspotClient.crm.objects.notes
```

**Comment by ohabash** [comment]
I cant figure out how to set `associationCategory` `associationTypeId` so that the note will get created on a contact or company. anyone have tips?
