### ISSUE TITLE
Why is it you need a node proxy to make calls to hs api from a react module hosted on it?

### ISSUE THREAD

**Issue by fluidnotions** [HubSpot/hubspot-api-nodejs#195]
I feel like I must be missing something here. But I've looked everywhere.  I have react hubspot modules but there is no way to make calls to the hubspot api which going through a proxy, because I don't want to expose the private app accessToken or worse the api key on a frontend. Surely there has to do another why else what is the point of react modules?

**Comment by atanasiuk-hubspot** [comment]
Hey @fluidnotions, you're correct, the SDK needs to be used on node.js side in order not to expose any credentials
