### ISSUE TITLE
How can I get all objects(both default and custom objects)?

### ISSUE THREAD

**Issue by potatozerg** [HubSpot/hubspot-api-nodejs#20]
My desire result: ['contacts', 'companies', etc...]
I need to get both default and custom objects.
I went through the doc but didn't find any.

**Comment by TommyCardello** [comment]
@potatozerg
I'm curious if you ever managed to get all custom objects with a single request?
For me, it is limited to 100.

**Comment by HenonoaH** [comment]
@potatozerg Did you have any luck on hunting objects list API?
