### ISSUE TITLE
Enroll/Unenroll contacts into Workflows

### ISSUE THREAD

**Issue by gugahoi** [HubSpot/hubspot-api-nodejs#200]
I've been looking through the docs and the source code to try to find the ability to `enroll` and `unenroll` contacts into Workflows or more broadly manage Workflows in general. I can't seem to find this documented anywhere so I am unsure how to achieve it. 

Note that this was supported in the [older SDK](https://github.com/HubSpotWebTeam/hs-node-api) that has been deprecated so I am confused on the status of things as this is the recommended replacement.

Here is the Hubspot Docs page for the relevant actions: https://developers.hubspot.com/docs/api/automation/create-manage-workflows

**Comment by ksvirkou-hubspot** [comment]
Hi @gugahoi .
Hubspot have not provided new Workflows API.
Exists only [legacy API ](https://legacydocs.hubspot.com/docs/methods/workflows/workflows_overview).
You can use it in old SDK or via `hubspotClient.apiRequest()`.

**Comment by paymog** [comment]
> Hi @gugahoi . Hubspot have not provided new Workflows API. Exists only [legacy API ](https://legacydocs.hubspot.com/docs/methods/workflows/workflows_overview). You can use it in old SDK or via `hubspotClient.apiRequest()`.

are there any plans to add support for this?
