### ISSUE TITLE
Build failing in TS projects that don't themselves need `@types/node-fetch`

### ISSUE THREAD

**Issue by zackdotcomputer** [HubSpot/hubspot-api-nodejs#208]
Using this package in a strict-mode Typescript project that doesn't, itself, have a requirement for `@types/node-fetch` causes a build error:
```
node_modules/@hubspot/api-client/lib/src/client.d.ts:30:53 - error TS7016: Could not find a declaration file for module 'node-fetch'. '/Users/zack/code/addition/api/node_modules/node-fetch/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/node-fetch` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-fetch';`

30     apiRequest(opts?: IHttpOptions): Promise<import("node-fetch").Response>;
```

This is because, as you can see above, the `client.d.ts` file that is generated for this project references `import("node-fetch")` in its own definitions of the Response type without requiring `@types/node-fetch` as a dependency (only as a devDependency, which is not transitively installed).

I think this can be fixed in one of two ways:
1. Make `@types/node-fetch` a dependency of this project (easy, but increases the weight of the package)
2. Redefine the important parts of the `Response` type in the package itself, eliminating the reference to the node-fetch `Response` type. (hard, but limits weight increase)

**Comment by ksvirkou-hubspot** [comment]
Hi @zackdotcomputer 
Thanks for reporting the issue.
I've moved `@types/node-fetch` to dependencies list.
You may see my changes in [version 8.3.2](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.3.2).
