### ISSUE TITLE
How can I pull the slack channel of a deal via API?

### ISSUE THREAD

**Issue by kobimantzur** [HubSpot/hubspot-api-nodejs#209]
Hi all!

I'm trying to send a slack message to a channel that is associated to the Hubspot deal as part of a Deal workflow.

I'm able to pull the Deal properties as part of the webhook I created, associations of contacts, and other custom objects I created but when it comes to getting the slack channel name I found zero documentation on how to pull this data using API.

Would appreciate your help.

This is how I pull the deal properties:
`    deal = await hubspotClient.crm.deals.basicApi.getById(
      dealId,
      DEAL_PROPERTIES,
      ["contacts"]
    );`

**Comment by ksvirkou-hubspot** [comment]
Hi @kobimantzur 
If I correctly understand you `the slack channel name` is a deal's custom property
if it is correct workable example bellow
example of getting a deal
```javascript
const response = await hubspotClient.crm.deals.basicApi.getById('11316935863', ['slack_channel_name'], ['dealname']);
```
example of getting deal's associated contacts
```javascript
  const response = await hubspotClient.crm.deals.associationsApi.getAll('11316935863', 'contacts');
```
