### ISSUE TITLE
HTTP Request Failed Error when using basic API

### ISSUE THREAD

**Issue by HenonoaH** [HubSpot/hubspot-api-nodejs#211]
I ran into some weird bug. I’m getting “HTTP Request Failed” error when using API,

`const { response } = await client.crm.contacts.basicApi.getPage(1, '0', properties);`

This error occurs only for some HubSpot accounts. Any hunches on this?

I’m using Node 16.4.2 and @hubspot/api-client: 5.0.0 version

Also, I suspect it fails only with this library, not with REST API

**Comment by barkermn01** [comment]
@HenonoaH  do this and you will no doubt see the problem for me on AWS Lambda it taking more than 40 seconds to load this library, as it currently stands looking at moving to https://github.com/MadKudu/node-hubspot will let you know if it works, before having to refactor all your code.

```js
const loadStart = new Date();
const hubspot = require('@hubspot/api-client');
console.log( `hubspot taken ${((new Date())-loadStart) /  1000)} to load `);
```

**Comment by ksvirkou-hubspot** [comment]
I ve just checked it 
and it works fine 
```javascript
const properties = ['email', 'firstname'];
const response = await hubspotClient.crm.contacts.basicApi.getPage(1, '0', properties);
```
try to update lib because 5.0.0 uses [depracated request](https://www.npmjs.com/package/request)
