### ISSUE TITLE
Batch associations

### ISSUE THREAD

**Issue by elarrat** [HubSpot/hubspot-api-nodejs#22]
We're working on a api to create/update contacts and deals into our hubspot account. Is there a way to associate deals to  contacts in batch?

**Comment by atanasiuk-hubspot** [comment]
Hi, @elarrat. Please take a look at [Create a batch of associations](https://developers.hubspot.com/docs/api/crm/associations) endpoint

**Comment by elarrat** [comment]
Alright, thanks a million.

**Comment by dshukertjr** [comment]
Hi!

I couldn't find any where to do batch create associations using this client, but am I correct? If so, why are we not doing this?
