### ISSUE TITLE
Cannot access Custom Objects

### ISSUE THREAD

**Issue by toddsutt** [HubSpot/hubspot-api-nodejs#225]
I cannot find any methods to access custom objects api. Am I missing something? I want to search through a specific custom object called "brand", I know how to do this with contacts, companies, and deals, but how can I do this with Custom Objects? Is this just not implemented yet? I believe the apis exist: https://developers.hubspot.com/docs/api/crm/crm-custom-objects

**Comment by nilatti** [comment]
@toddsutt did you ever get an answer to this or figure it out? I'm having the same problem.

**Comment by toddsutt** [comment]
> @toddsutt did you ever get an answer to this or figure it out? I'm having the same problem.

Nilatti, I did find a workaround for this. When you look at the developer docs, it suggests doing `hubspotClient.crm.basicApi.getPage(objectType, limit, after, properties, propertiesWithHistory, associations, archived);` - but this does not work!

Instead, you need to do a custom request like the following example for a search for a custom object called "Brand":

```
const brandSearchResponse = await hubspotClient.apiRequest({
      method: 'post',
      path: '/crm/v3/objects/brand/search',
      body: {
        "filterGroups": [
          {
            "filters": [
              { value: "MyBrand", propertyName: 'name', operator: 'EQ' }
            ]
          }
        ],
        "sorts": ["name"],
        "properties": ["name"],
        "limit": 1,
        "after": 0
      }
    });
```

**Comment by nilatti** [comment]
@toddsutt super helpful, thank you so much!!

**Comment by ksvirkou-hubspot** [comment]
Hi @nilatti @toddsutt  
the docs are incorrect 
You can use 
```javascript
objectsResponse = await hubspotClient.crm.objects.basicApi.getPage(
          objectTypeId,
          OBJECTS_LIMIT,
          after,
          properties
        );
```
also you can check [the custom objects sample app](https://github.com/HubSpot/sample-apps-custom-object/tree/main/node)

**Comment by toddsutt** [comment]
> Hi @nilatti @toddsutt the docs are incorrect You can use
> 
> ```js
> objectsResponse = await hubspotClient.crm.objects.basicApi.getPage(
>           objectTypeId,
>           OBJECTS_LIMIT,
>           after,
>           properties
>         );
> ```
> 
> also you can check [the custom objects sample app](https://github.com/HubSpot/sample-apps-custom-object/tree/main/node)

Thank you for this! I will check this out and rewrite my code to be cleaner if this works
