### ISSUE TITLE
Argument of type 'ReadStream' is not assignable to parameter of type 'HttpFile'

### ISSUE THREAD

**Issue by JeffinJ** [HubSpot/hubspot-api-nodejs#228]
while importing contacts using .csv file, following the steps in the documentation gives me this error: "Argument of type 'ReadStream' is not assignable to parameter of type 'HttpFile'"

`const importFileReadStream = fs.createReadStream(fileName)
 const importResponse = await hubspotClient.crm.imports.coreApi.create(importFileReadStream, JSON.stringify(importRequest));
`

**Comment by ksvirkou-hubspot** [comment]
Hi @JeffinJ 
I think it must be something like this
```Javascript
const file = {
    data: fs.createReadStream(fileName),
    name: 'filename'
}
const result = await hubspotClient.crm.imports.coreApi.create(file, JSON.stringify(importRequest))
```
alse you can check [node import sample app](https://github.com/HubSpot/sample-apps-imports/tree/master/node/src)

**Comment by JeffinJ** [comment]
> Hi @JeffinJ I think it must be something like this
> 
> ```js
> const file = {
>     data: fs.createReadStream(fileName),
>     name: 'filename'
> }
> const result = await hubspotClient.crm.imports.coreApi.create(file, JSON.stringify(importRequest))
> ```
> 
> alse you can check [node import sample app](https://github.com/HubSpot/sample-apps-imports/tree/master/node/src)

Yes tried that and working with that fix. There is still a Type error though. I had to ignore it.

**Comment by ksvirkou-hubspot** [comment]
> > Hi @JeffinJ I think it must be something like this
> > ```js
> > const file = {
> >     data: fs.createReadStream(fileName),
> >     name: 'filename'
> > }
> > const result = await hubspotClient.crm.imports.coreApi.create(file, JSON.stringify(importRequest))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > alse you can check [node import sample app](https://github.com/HubSpot/sample-apps-imports/tree/master/node/src)
> 
> Yes tried that and working with that fix. There is still a Type error though. I had to ignore it.

Could you share your code, please?
