### ISSUE TITLE
Error: The mediaType text/html is not supported by ObjectSerializer.parse.

### ISSUE THREAD

**Issue by simllll** [HubSpot/hubspot-api-nodejs#240]
`hubspotClient.crm.owners.ownersApi.getById`
throws this error since today? 

Is it a backend issue? Or where there some changes which are not yet reflected in this library?

Thanks
Simon

**Comment by simllll** [comment]
Interesting, the request returns 404 not found:
Request: /crm/v3/owners/50564106

Returns: '<html>\n' +
    '<head>\n' +
    '<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>\n' +
    '<title>Error 404 Not Found</title>\n' +
    '</head>\n' +
    '<body><h2>HTTP ERROR 404</h2>\n' +
    '<p>Resource not found</p>\n' +
    '</body>\n' +
    '</html>\n',

**Comment by simllll** [comment]
Alright, the issue turned out to be related with a deleted owner. Besides that, the library currently makes it hard to catch this error, as it only throws the mediaType is not suppored error insteda of a 404 or smthg.
This should be fixed in the openapi generator already though  (https://github.com/OpenAPITools/openapi-generator/pull/12459). I'm I assuming that this library uses the generator? Would be great to bring this patch in here too.

How to reproduce: just retrieve a owner that doesn't exist` hubspotClient.crm.owners.ownersApi.getById(1234);`

**Comment by ksvirkou-hubspot** [comment]
I ve just checked it and it works correctly on version 7.1.2
it throws error 404

**Comment by simllll** [comment]
Strange, we are using this version too... What nod exception do you get?

**Comment by ksvirkou-hubspot** [comment]
> Strange, we are using this version too... What node exception do you get?

v18.4.0

**Comment by simllll** [comment]
We are on node 16, but this is not related to this exception.
the problem is when the ObjectSerializer gets something to parse that is not content type applicatoin/json.
see here:
![image](https://user-images.githubusercontent.com/5757263/186871776-92d7f746-520a-46d2-a62a-2b7af011bff4.png)

then it throws just:
`throw new Error("The mediaType " + mediaType + " is not supported by ObjectSerializer.parse.");`
and this one doesn't give any insights on the error itself (e.g. 404 or whatever).

**Comment by ksvirkou-hubspot** [comment]
Could You check your package lock?
because it is fixed in the latest vesrion 
https://github.com/HubSpot/hubspot-api-nodejs/blob/7.1.2/codegen/crm/owners/models/ObjectSerializer.ts

**Comment by ksvirkou-hubspot** [comment]
it was released in 7.0.0
https://github.com/HubSpot/hubspot-api-nodejs/blob/7.0.0/codegen/crm/owners/models/ObjectSerializer.ts

**Comment by simllll** [comment]
Oha, indeed, .. I could swear I checked the package.json of th ehubspot library just yesterday and it was saying 7.1.2.. but it seems I was wrong. Sorry for the confusion and thanks for your support! :)
