### ISSUE TITLE
Import is a Massive 2.4mb, gives me issues building the server in Nuxt 3

### ISSUE THREAD

**Issue by daver987** [HubSpot/hubspot-api-nodejs#241]
![Fails to build](https://user-images.githubusercontent.com/85001306/183742390-65a033f1-e969-45a9-9275-94d9bf4ce8c7.jpg)
![Only way to get it to build](https://user-images.githubusercontent.com/85001306/183742395-a3e1af19-42a5-46e6-94c2-7b2228fc1bda.jpg)
![hubspot client huge](https://user-images.githubusercontent.com/85001306/183742396-529b1a9a-6c18-4d82-9358-3d692fa4b560.jpg)

The only way that I could build the server was to increase the memory in node, I had to go back and use regular fetch calls to get it to work and deploy.

**Comment by ksvirkou-hubspot** [comment]
@atanasiuk-hubspot

**Comment by barkermn01** [comment]
i would also like to confirm that node runtime has to unpack this and is using 10.2 MB after unpacking this is unable in any sort of real-world application.

![image](https://user-images.githubusercontent.com/37368/194865337-970d02a1-226c-4396-ba27-68c17b8595e3.png)

Also in the same vein when using this inside AWS Lambda it is adding > 40 seconds of load time just to load the module, that is no other code but a console.log after requiring the library...

This needs fixing as a CRITICAL problem, and how this got through QA or any testing when it's violating 30 timeouts is an absolute joke.

**Comment by zaq42** [comment]
Running in an AWS EC2 instance, I've seen this slow from about 6s to around 28 seconds, just for the single line:
```  const hubspot = require('@hubspot/api-client');```

Something changed between the 9th and the 12th of September. Before the change, consistently 5-6 seconds, after the change it has never been quicker than 25s.

I'm using 7.1.2, but also see slow performance from 7.0.1.

In docker on an M1 MacBook, it has slowed down from about 1.5s to nearly 7s.  Again, this is now consistently slow.

(Using node 16.17.0)

**Comment by daver987** [comment]
I had to dump this package and just use regular fetch calls from the server side. I mean they did decide on Jinjava for a language of choice so that should say a lot. I can’t recall ever seeing a package this large, it’s not even tree shakable. Realistically it’s just a few helper functions to make our lives easier, it’s not supposed to make things more difficult. HS is a fantastic product on the consumer side, but definitely not of the development side.

Sent from my iPhone

On Oct 18, 2022, at 21:55, zaq42 ***@***.***> wrote:

﻿

Running in an AWS EC2 instance, I've seen this slow from about 6s to around 28 seconds, just for the single line:
const hubspot = ***@***.***/api-client');

Something changed between the 9th and the 12th of September. Before the change, consistently 5-6 seconds, after the change it has never been quicker than 25s.

I'm using 7.1.2, but also see slow performance from 7.0.1.

In docker on an M1 MacBook, it has slowed down from about 1.5s to nearly 7s. Again, this is now consistently slow.

(Using node 16.17.0)

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
Thank you for reporting this issue.
We have understand these problems.
This SDK is autogenerated and it is the reason of these problems.
This SDK is created for backandd development (node js) and on back end side these probles are less sensetive.
We have done some optimization ([more details here](https://github.com/HubSpot/hubspot-api-nodejs/issues/249)).
But it doesn’t solve these problems.
If have any idea how to improve this SDK, feel free to create issue.
Closing this for now.
