### ISSUE TITLE
Could you share the openapi configs / template used to generate this?

### ISSUE THREAD

**Issue by Translucent504** [HubSpot/hubspot-api-nodejs#242]
I'm interested in generating C# client lib, but the method names generated by default arent very readable.

For example to get paged contacts, the C# generated name is `GetCrmV3ObjectsContactsGetPageAsync` based on operationIds, While in this library the generated method name is just `getPage`:
https://github.com/HubSpot/hubspot-api-nodejs/blob/918a11c82924a23a445bfc0b6ae9b85a4a418f43/codegen/crm/contacts/apis/BasicApi.ts#L207

**Comment by ksvirkou-hubspot** [comment]
@atanasiuk-hubspot

**Comment by atanasiuk-hubspot** [comment]
There is nothing we can share at the moment, but generally method name can be extracted from operationId:
`get-/crm/v3/objects/contacts_getPage` => `getPage`. Some kind of operationId transformation is needed here.

**Comment by chivandikwa** [comment]
@Translucent504 Are you using nswag studio by any chance. I may be able to provide more information to use templates to overcome this. I had the same problem

**Comment by atanasiuk-hubspot** [comment]
Feel free to reopen if any updates
