### ISSUE TITLE
Allow passing `agent' to node-fetch

### ISSUE THREAD

**Issue by dtikhonov-iex** [HubSpot/hubspot-api-nodejs#243]
This would make it possible to use an HTTP proxy.

**Comment by ksvirkou-hubspot** [comment]
Do you mean `User-Agent`?

**Comment by dtikhonov-iex** [comment]
No, I mean this:

https://github.com/node-fetch/node-fetch#custom-agent

**Comment by ksvirkou-hubspot** [comment]
Hi @dtikhonov-iex .
Any reason for adding it?

**Comment by dtikhonov-iex** [comment]
Yes.  So that one could specify an HTTP proxy.

**Comment by ksvirkou-hubspot** [comment]
The ability to change http agent is available in [9.0.0-beta.2 version](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.2).
Could you check it, please?
Is it work as expected?
@dtikhonov-iex

**Comment by dtikhonov-iex** [comment]
I'll test this if you promise to backport this fix to 7.x! 🙂

**Comment by ksvirkou-hubspot** [comment]
[7.2.0](https://www.npmjs.com/package/@hubspot/api-client/v/7.2.0)

**Comment by ksvirkou-hubspot** [comment]
@dtikhonov-iex 
Have you checked it by any chance?
