### ISSUE TITLE
Missing oauth methods in schema coreApi

### ISSUE THREAD

**Issue by Celine68** [HubSpot/hubspot-api-nodejs#245]
When I try to use some methods from the schema CoreApi, authenticating through oauth2, I get the following error message :
```
Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at [...].
```
I found out that the oauth2 authentication method was missing from some of the schema CoreApi methods.

I made a [PR](https://github.com/HubSpot/hubspot-api-nodejs/pull/238) to try to solve this problem, but I have no news about it.
Since the authentification through apiKey is not going to work anymore starting on the 30th of november 2022, it starts to get urgent.

Thank you for your time.

**Comment by ksvirkou-hubspot** [comment]
Hi @Celine68 
I've fixed it
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.0)?

**Comment by Celine68** [comment]
Thank you @ksvirkou-hubspot . I'm going to try it.
