### ISSUE TITLE
❌ Wrong documentation about creating CSV import 

### ISSUE THREAD

**Issue by dkonopka** [HubSpot/hubspot-api-nodejs#246]
So, I was trying to create an import via CSV file and waste a few minutes because of wrong documentation in README.

https://github.com/HubSpot/hubspot-api-nodejs#first-option-with-fsreadstream README.md say:
```js
const importFileReadStream = fs.createReadStream(fileName)
```

which is not true.

it should be:

```js
const importFileReadStream = {
    data: fs.createReadStream( fileName),
    file: fileName
};
```

Just to let you know, I was getting such error:
```
TypeError: Cannot read properties of undefined (reading 'name')
```

**Comment by ksvirkou-hubspot** [comment]
Thank you for issue 
I ve just fixed it
