### ISSUE TITLE
Wrong operation for iterating an array

### ISSUE THREAD

**Issue by LarryYarianTraction** [HubSpot/hubspot-api-nodejs#247]
I recently encountered an issue with the ObjectSerializer for array types.  When serializing arrays, the code should be using `for ... of ...` instead of `for ... in ...`.

https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/contacts/models/ObjectSerializer.ts#L163-L170

For reasons I won't go into here, I have some code which added a function to the prototype for the `Array` type.  This caused the serializer to create empty objects for serialized `Array<>` types of object arrays and adding `null` for serialized primitive type array.

**Comment by ksvirkou-hubspot** [comment]
Thank you for reporting the issue.
I've just changed `for in` to `for of` in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.0).
