### ISSUE TITLE
Missing property on Error Type of BatchResponseSimplePublicObjectWithErrors

### ISSUE THREAD

**Issue by co-sic** [HubSpot/hubspot-api-nodejs#25]
The Error type is missing the property "category", which is included in the response of the batchApi (Tested with contacts.batchApi.read). I want to check if the error is a 404 and the best way to do that would be to check if the category is "OBJECT_NOT_FOUND". As a workaround i could check the included message or do a typecast to get access to the category property. But would be nice to have the property included in the typedefinitions.

**Comment by ksvirkou-hubspot** [comment]
Hi @co-sic 
Thank you for reporting this issue.
It has been fixed in version [9.1.0](https://www.npmjs.com/package/@hubspot/api-client/v/9.1.0).
