### ISSUE TITLE
Add contact to a list

### ISSUE THREAD

**Issue by garciapd** [HubSpot/hubspot-api-nodejs#250]
Hi all, i'm getting a bit frustrated as I don't find how to add a contact to a static list i have created, can somebody help me please?

Thanks

**Comment by ksvirkou-hubspot** [comment]
Hi @garciapd 
You can't add contact using this SDK
API for it doesn't exist in v3

**Comment by garciapd** [comment]
Ok thanks, that makes sense, I have used the wrapped call for non implemented endpoints.
