### ISSUE TITLE
Unable to search products using operator IN

### ISSUE THREAD

**Issue by koskinenaa** [HubSpot/hubspot-api-nodejs#251]
I'm trying to do a product search in a workflow custom code block. The search is done with known skus, one or more, to find out the corresponding HubSpot product ids for further processing.

I pass the following search request object
```
const PublicObjectSearchRequest = {
  filterGroups: [{
    "filters":[{
      "values": ["foo", "bar"],
      "propertyName":"hs_sku",
      "operator":"IN"
    }]
  }]
};
```
to the API client.
```
const apiResponse = await hubspotClient.crm.products.searchApi.doSearch(PublicObjectSearchRequest);
```
However I keep getting the following error,

> Invalid input JSON on line _x_, column _y_: Cannot construct instance of `com.hubspot.inbounddb.publicobject.core.v3.search.Filter`, problem: operator IN requires values

Am I doing something wrong here or is this a "feature" of the api client?

**Comment by ksvirkou-hubspot** [comment]
Hi @koskinenaa 
This code are workable for latest versions 
In workflow custom code use version 3.4.1 (in this version param values doesn't support only value)

**Comment by koskinenaa** [comment]
Hi, @ksvirkou-hubspot ,

Thank you for your reply. Would you happen to have any insight, if the values support is coming to the workflow custom core anytime soon? 

I already conjured up a workaround for the problem with a loop, but it is not quite ideal and I would prefer fetching the data in a one call to the loop setup.

**Comment by ksvirkou-hubspot** [comment]
Sorry 
but I have no information about it
@koskinenaa
