### ISSUE TITLE
Hubspot property number type

### ISSUE THREAD

**Issue by AlexThomas90210** [HubSpot/hubspot-api-nodejs#253]
When querying the properties API, is there any way to figure out if the number is a decimal or int. Looking to create parquet files from the response but would need to know the type of number that is in the property first by querying the properties API however it only says that its a number

**Comment by ksvirkou-hubspot** [comment]
Hi @AlexThomas90210 
Hubspot API have no way to figure out if the number is a decimal or int, as far as I could find out.
