### ISSUE TITLE
Question: Did you remove bottleneck as a limiter? What are the SDK using now to limit the 100 request each 10 seconds?

### ISSUE THREAD

**Issue by jeffersonlipsky** [HubSpot/hubspot-api-nodejs#254]
Hello! 
Right now I am using the version 3.4.1 but I have some concern  when the time to update the version arrives. 

- Did you remove bottleneck as a limiter? 
- What is the SDK using now to limit the 100 request each 10 seconds?
- If It is using a limiter, How can I know if there are requests in process? (Like, Are there jobs in the queue?)
- Would I have to build the limiter in the new versions (>5)?

Thank you so much :D

**Comment by gwhobbs** [comment]
I wound up just wrapping all the API methods I used with Bottleneck's `wrap()`; it's disappointing that this was removed as it's very easy to run into HubSpot's API limits without some sort of client-side limiter. It does look like Bottleneck is still a package dependency though…

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've just added bottleneck as a limiter.
You can find it in [the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/8.7.0).
