### ISSUE TITLE
PublicObjectSearchRequest's type definition is wrong

### ISSUE THREAD

**Issue by naorpeled** [HubSpot/hubspot-api-nodejs#255]
Hey,
at the moment the TS definition of PublicObjectSearchRequest states that most properties are required but they're actually not.

For example:
```typescript
	export class PublicObjectSearchRequest {
	    'filterGroups': Array<FilterGroup>;
	    'sorts': Array<string>;
	    'properties': Array<string>;
	    'limit': number;
	    'after': number;
	...
	}
```

Shall I create a PR to resolve this?

**Comment by ksvirkou-hubspot** [comment]
Hi @naorpeled 
We can't change codegen
I try to ask Hubspot to change the swagger files

**Comment by ksvirkou-hubspot** [comment]
All properties of thePublicObjectSearchRequest class became optional in [the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.1).
