### ISSUE TITLE
getAllContacts is generating 429 error code

### ISSUE THREAD

**Issue by nomoney4me** [HubSpot/hubspot-api-nodejs#256]
It seems that maybe .getAllContacts() is calling things too fast and hitting Hubspot's limit for calls/sec?
Per https://developers.hubspot.com/docs/api/usage-details it seems that the limit is 4:
`The [Search API](https://developers.hubspot.com/docs/api/crm/search) endpoints are rate limited to four requests per second per authentication token.`

![image](https://user-images.githubusercontent.com/9965349/200951655-57633087-ec9b-4156-bbbf-40565b3b6efb.png)

Note: hsClient.crm.contacts.getAll() might be the culprit

**Comment by AbdelrahmanHafez** [comment]
An old project I've been working on is having this issue.

I think the hubspot client should retry automatically if 429 was received, and read the response headers to see how long the API call needs to wait, IMO this should be the default, or at least an option.

One way I usually achieve that in my projects is by using the HTTP client [got](https://www.npmjs.com/package/got) which has this retry mechanism with smart 429 handling turned on by default. Using it internally in your client would give a much nicer developer experience for your client users.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
Mechanism of retry is under development now.
I'll inform you as soon as it's done.

**Comment by ksvirkou-hubspot** [comment]
I've added `numberOfApiCallRetries`.
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.4.0)?
