### ISSUE TITLE
is {numberOfApiCallRetries: NumberOfRetries.Six} deprecated in the latest version?  

### ISSUE THREAD

**Issue by LIIIIINN** [HubSpot/hubspot-api-nodejs#258]
I updated api-client version from 5.0.0 to 7.1.2, and found numberOfApiCallRetries is actually missing, which caused a type error in my code. Since I didnt find any relevant change log here,  just wanna confirm is this field deprecated?  If so, any alternative for this field? Thanks

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
`numberOfApiCallRetries` is under development now.
As soon as it will be done I

**Comment by ksvirkou-hubspot** [comment]
I've added `numberOfApiCallRetries`.
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.4.0)?
