### ISSUE TITLE
batchApi update method is not working and returns success with empty array

### ISSUE THREAD

**Issue by jacquesfu** [HubSpot/hubspot-api-nodejs#26]
I inferred the expected structure of your batch update based on your public API docs and the batch create in this libraries readme. 

However, it would be helpful if you had an example of how to do a batch update. The bigger problem though is that I believe it is broken.

I've constructed a curl call via API and this works
```
curl --location --request POST 'https://api.hubapi.com/crm/v3/objects/deals/batch/update?hapikey=redacted' \
--header 'content-type: application/json' \
--data-raw '{
  "inputs": [
    {
      "id": "859408635",
      "properties": {
        "amount": "2"
      }
    }
  ]
}'
```

However, when I attempt to perform the same using your library, it does not update the record but neither does it throw any errors.

```
  const dealRecord = [{ id: "859408635", properties: { amount: "1" } }];
  const response = hubspot.crm.deals.batchApi.update(dealRecord);
console.log(response.body.results); //result is []
```

If this is the incorrect way to perform batch updates can you document that right way?

**Comment by atanasiuk-hubspot** [comment]
Hi, @jacquesfu thank you for the feedback, we're working on improving of SDK docs

> However, when I attempt to perform the same using your library, it does not update the record but neither does it throw any errors.

You're probably missing `inputs` key. Please, try the following:
```
const dealRecord = { id: "859408635", properties: { amount: "1" } };
const response = hubspot.crm.deals.batchApi.update({ inputs: [dealRecord] });
```

**Comment by jacquesfu** [comment]
@atanasiuk-hubspot ah got it, perhaps throw an exception then if you know inputs are required for the batch update. I'll test it out and let you know, thanks for responding so quickly.

**Comment by jacquesfu** [comment]
@atanasiuk-hubspot it works, please review my pull request to update the documentation for others https://github.com/HubSpot/hubspot-api-nodejs/pull/28

**Comment by atanasiuk-hubspot** [comment]
Sure, thanks @jacquesfu for contributing to docs.
