### ISSUE TITLE
@hubspot/api-client v8.0.0 typescript compile errors

### ISSUE THREAD

**Issue by rcbevans** [HubSpot/hubspot-api-nodejs#262]
I'm trying to bump our @hubspot/api-client dependency to v8.0.0 from v7.1.2 and our webpack build fails with the updated dependency giving hundreds of errors like the following:

```
ERROR in ./node_modules/@hubspot/api-client/lib/src/discovery/webhooks/WebhooksDiscovery.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for /home/rich/source/meetingplan/packages/server/node_modules/@hubspot/api-client/lib/src/discovery/webhooks/WebhooksDiscovery.d.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
See: https://github.com/Microsoft/TypeScript/issues/12358
    at makeSourceMapAndFinish (/home/rich/source/meetingplan/packages/server/node_modules/ts-loader/dist/index.js:52:18)
    at successLoader (/home/rich/source/meetingplan/packages/server/node_modules/ts-loader/dist/index.js:39:5)
    at Object.loader (/home/rich/source/meetingplan/packages/server/node_modules/ts-loader/dist/index.js:22:5)
 @ ./node_modules/@hubspot/api-client/lib/src/discovery/ sync ^\.\/.*$ ./webhooks/WebhooksDiscovery.d.ts ./webhooks/WebhooksDiscovery.d
 @ ./node_modules/@hubspot/api-client/lib/src/services/initObject.js 5:26-57
 @ ./node_modules/@hubspot/api-client/lib/src/client.js 15:21-53
 @ ./node_modules/@hubspot/api-client/lib/index.js 4:15-38
```

Each error is for a different `./node_modules/@hubspot/api-client/lib/src/**/*.d.ts` file.

On top of this, and possibly related, I'm seeing some APIs like `client.crm.deals.searchApi.doSearch` which used to return `CollectionResponseWithTotalSimplePublicObjectForwardPaging`, or `client.crm.companies.batchApi.read` which used to return `BatchResponseSimplePublicObjectWithErrors` are now returning `any` flagging new type errors in existing code.

**Comment by atanasiuk-hubspot** [comment]
Hey @rcbevans, could you maybe provide minimal webpack setup to repro the issue?

**Comment by harry-peirse** [comment]
Hi, I am also seeing lots of typescript errors when trying to update. It appears a lot of the types are missing, or at least have been replaced by `any`. The client.d.ts file in my node_modules directory looks like this with 7.1.2:

```
export declare class Client {
    automation: AutomationDiscovery;
    cms: CmsDiscovery;
    communicationPreferences: CommunicationPreferencesDiscovery;
    conversations: ConversationsDiscovery;
    crm: CrmDiscovery;
    events: EventsDiscovery;
    marketing: MarketingDiscovery;
    oauth: OauthDiscovery;
    settings: SettingsDiscovery;
    webhooks: WebhooksDiscovery;
    config: IConfiguration;
    constructor(config?: IConfiguration);
    init(): void;
    setAccessToken(token: string): void;
    setApiKey(apiKey: string): void;
    setDeveloperApiKey(developerApiKey: string): void;
    apiRequest(opts?: IHttpOptions): Promise<import("node-fetch").Response>;
}
```

but with 8.0.0 it looks like this:
```
export declare class Client {
    config: IConfiguration;
    protected _automation: any;
    protected _cms: any;
    protected _communicationPreferences: any;
    protected _conversations: any;
    protected _crm: any;
    protected _events: any;
    protected _files: any;
    protected _marketing: any;
    protected _oauth: any;
    protected _settings: any;
    protected _webhooks: any;
    constructor(config?: IConfiguration);
    resetDiscoveries(): void;
    get automation(): any;
    get cms(): any;
    get communicationPreferences(): any;
    get conversations(): any;
    get crm(): any;
    get events(): any;
    get files(): any;
    get marketing(): any;
    get oauth(): any;
    get settings(): any;
    get webhooks(): any;
    setAccessToken(token: string): void;
    setApiKey(apiKey: string): void;
    setDeveloperApiKey(developerApiKey: string): void;
    apiRequest(opts?: IHttpOptions): Promise<import("node-fetch").Response>;
}
```

And this is leading to issues wherever we iterate on a collection, eslint is complaining that it doesn't have enough type information, for example `TS7006: Parameter 'hsOwner' implicitly has an 'any' type.`

**Comment by harry-peirse** [comment]
Looking through the commit log on this repo, it looks like [this commit](https://github.com/HubSpot/hubspot-api-nodejs/commit/6b4aab265f7e927f070e6990db482a0e29510b3d) basically erased all the types - I haven't dug into it enough to figure out the reason, maybe there is a good one, but from a developer experience perspective it seems a really bad idea to do this - I can't see us justifying upgrading when the types are so ambiguous, it basically makes the fact that this is typescript meaningless.

**Comment by ksvirkou-hubspot** [comment]
I've fixed it
Could you check [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.1)?

**Comment by rcbevans** [comment]
I'll give it a try after the long weekend and get back to you, thanks!

**Comment by ksvirkou-hubspot** [comment]
I ve created [PR](https://github.com/HubSpot/hubspot-api-nodejs/pull/267)
if everything ok I ll publish it on Monday

**Comment by ksvirkou-hubspot** [comment]
> I ve created [PR](https://github.com/HubSpot/hubspot-api-nodejs/pull/267) if everything ok I ll publish it on Monday

I ve just released it 
v 8.1.0

**Comment by rcbevans** [comment]
Just tested with 8.1 and after some config changes to ignore the .d.ts and .js.map files, everything seems to be working fine.

**Comment by ksvirkou-hubspot** [comment]
if changes are needed on my side contact me
Can I close the issue?

**Comment by harry-peirse** [comment]
Thanks very much - seems ok for me too!
