### ISSUE TITLE
Incorrect missing scope for Owners API

### ISSUE THREAD

**Issue by wong-zq** [HubSpot/hubspot-api-nodejs#268]
```ts
// hubspot client
const HubspotClient = new Client({ accessToken });

// some owner id
const id = 123456;

// hubspot api request to get the owner
const owner = await HubspotClient.crm.owners.ownersApi.getById(id);
```

When making this request, the error message that shows up is:
```json
{
  "status": "error",
  "message": "This app hasn't been granted all required scopes to make this call. Read more about required scopes here: https://developers.hubspot.com/scopes.",
  "correlationId": "...",
  "errors": [
    {
      "message": "One or more of the following scopes are required.",
      "context": {
        "requiredScopes": [
          "contacts"
        ]
      }
    }
  ],
  "links": {
    "scopes": "https://developers.hubspot.com/scopes"
  },
  "category": "MISSING_SCOPES"
}
```

Specifically, it mentions that the `requiredScopes` are `contacts` when it is actually `owners`.

Also, please it should be `crm.objects.owners.read` specifically, to avoid any confusion.

**Comment by ksvirkou-hubspot** [comment]
Hi @wong-zq 
You have to add required scopes in your hubspot account

**Comment by wong-zq** [comment]
@ksvirkou-hubspot I did add the scope 'contacts'. However, what was required was actually `owners`. Once I added `owners` it worked. All I'm saying it that the error message returned from the API is incorrect.

If you read the error response, it says that the `requiredScopes` was `contacts`, when it is  actually supposed to be `owners`.

**Comment by wong-zq** [comment]
@ksvirkou-hubspot if this repo doesn't handle that error, at which repo should I file the issue?

Cuz I understand that this is just a NodeJS wrapper for the actual API. But I'm not sure which repo the actual API is.

**Comment by ksvirkou-hubspot** [comment]
I don't know exactly 
You can try https://help.hubspot.com/

**Comment by ksvirkou-hubspot** [comment]
Looks like the issue is resolved now.
