### ISSUE TITLE
Unable to associate contact with ticket on the latest version of the client 

### ISSUE THREAD

**Issue by batflarrow** [HubSpot/hubspot-api-nodejs#273]
On the latest version of the client, I am getting this error when trying to associate a ticket with a contact. Same code is working on the older version.
```
  await this.client.crm.tickets.associationsApi.create(
      ticketId,
      "contacts",
       contactId,
      "ticket_to_contact"
    );
```
ApiException [Error]: HTTP-Code: 500
Message: An error occurred.
Body: `{"status":"error","message":"internal error","correlationId":"..."}`
    at AssociationsApiResponseProcessor.<anonymous>
    at Generator.next (<anonymous>)
    at fulfilled 
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 500,
  body: {
    status: 'error',
    message: 'internal error',
    correlationId: '...'
  }
}

**Comment by ksvirkou-hubspot** [comment]
We are working on it

**Comment by arunpugahz** [comment]
The same thing happens when we associate a deal with a contact

**Comment by b8ne** [comment]
Looks to be an issue with the v4 URL used, example [here](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/tickets/apis/AssociationsApi.ts#L122) .
`associationType ` is replaced in, however there is no param for it in the original path.

**Comment by arunpugahz** [comment]
Yep, it worked. 👍
