### ISSUE TITLE
Incompatibility issue on node SDK between New version (8.0.0) and old one (5.0.0)

### ISSUE THREAD

**Issue by LIIIIINN** [HubSpot/hubspot-api-nodejs#277]
Hi, recently, I was trying to upgrade to the latest version of hubpsot api-sdk, but got many failures on methods like product. create etc. Looking into the issues, I found there are two issues that didnt exist on the older version: 
1. problem: Names for properties should be lowercase and have less than 100 characters.
2. Invalid names: 
Just wonder is the newer version able to support backwards compatability?  Is this a potential bug for the latest one? How long we can use 5.0.0 version until it is deprecated? 
Thanks

**Comment by ksvirkou-hubspot** [comment]
Hi @LIIIIINN 

1) Could you give me an example, please?as I see (for example crm.contacts) approximately all names are the same in 5.0.0 and in 8.0.0
2) in 5.0.0 we used request lib and it was deprecated that is why we had used the other generator 
5.0.0=>6.0* (or higher) no backwards compatibility 
6.0.0=>7.0.0 backwards compatibility 
How long we can use 5.0.0 version until it is deprecated? 
I can't say maybe a few month
but some methods can work incorrect in 5.0.0

**Comment by LIIIIINN** [comment]
hi @ksvirkou-hubspot , thanks for your reply. 
1. the affected crm members include, companies, properties, associations, products, which all have the same errs happening, covering create, batch, delete, get, I didnt try all of them through by sending a curl to testify each, instead they are  from our testing results,  but one of api request I made is **companies.create** interface , which is as below: 
```
curl --request POST \
  --url https://api.hubapi.com/crm/v3/objects/companies \
  --header 'authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
  --header 'content-type: application/json' \
  --data '{
  "properties": {"domain":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.dev.localhost","name":"xxxxxxxxxxxxt Test Company clb39jn1f0000ldm8blqza3se","admins":"test1@mailinator.com","teamMembers":"test1@mailinator.com","trialStarted":"2022-11-30T06:24:43.107Z","leadSource":"Unit Test","discountCode":"TEST","referralCode":"TEST","cancelationMessage":"Testing","stage":"Trialing"} 
}'

response: 
{"status":"error","message":"Invalid input JSON on line 3, column 1: Cannot construct instance of `com.hubspot.inbounddb.publicobject.core.v2.SimplePublicObjectInput`, problem: Names for properties should be lowercase and have less than 100 characters. Invalid names: [discountCode, leadSource, referralCode, cancelationMessage, teamMembers, trialStarted]","correlationId":"495e00db-dcc5-4f5d-832e-440d3ad00470"}%               
```
under version 5.0.0, it is all working fine, after switching to 7.XX or 8.0.0, almost all the interfaces we need are failing. 

Thanks!

**Comment by LIIIIINN** [comment]
Thanks for your swift response @ksvirkou-hubspot! so wanna confirm is my understanding correct that the error is mainly about on key names that is having an invalid formatting issue? Like we using `camelCase`? I will check our code cause we do maintain a mapping to translate between these two naming conventions. Thanks heaps mate! and will let you know if I got other different errs.

**Comment by ksvirkou-hubspot** [comment]
Correct 
the error is mainly about on key names
