### ISSUE TITLE
CRM v3 Associations endpoints do not have support for breaking change announced October 2020?

### ISSUE THREAD

**Issue by austinbirch** [HubSpot/hubspot-api-nodejs#29]
HubSpot [announced a breaking change](https://developers.hubspot.com/changelog/announcing-a-change-to-how-v3-crm-apis-return-association-data) for responses that return associations data back in October 2020. This change is planned to go live on January 18th.

I’ve been double-checking our support for this and I’ve found that most of the endpoints are already covered by this library (including the ability to pass `paginateAssociations=true` to get the new behaviour now).

However, it looks like the associations endpoints have been missed?

As an example, the `/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read` endpoint cannot be called in this library with `paginateAssociations=true`, and the it looks like the response types do not include the potential paging data that will be returned when there are more than 100 association results.

```
{
    "status": "COMPLETE",
    "results": [
        {
            "from": {
                "id": "1"
            },
            "to": [
                // 100 items
            ],
           // no return types for the following paging information
            "paging": {
                "next": {
                    "after": "...",
                    "link": "..."
                },
                "prev": null
            }
        }
    ],
    "startedAt": "2021-01-08T13:30:44.078Z",
    "completedAt": "2021-01-08T13:30:44.086Z"
}
```

I think this actually means that when the breaking change goes live on the 18th of January, anybody using the associations endpoint won't be able to fetch the additional pages of results?

If you are relying on the associations endpoint today, and expect more than 100 results for some items, I think the only workaround for now is to make calls to that endpoint using `hubspotClient.apiRequest` as described in the [README](https://github.com/HubSpot/hubspot-api-nodejs#not-wrapped-endpoints).

**Comment by ksvirkou-hubspot** [comment]
Hi @austinbirch .
I added it in [8.4.0](https://www.npmjs.com/package/@hubspot/api-client/v/8.4.0) version and I've just checked and it works correctly.
I recommend you to check `crm.associations.v4` (it was added in version [8.6.0](https://www.npmjs.com/package/@hubspot/api-client/v/8.6.0)).
We will fully migrate to v4 in future.
