### ISSUE TITLE
AWS Lambda cannot find module ../discovery/crm/CrmDiscovery

### ISSUE THREAD

**Issue by Chris59160** [HubSpot/hubspot-api-nodejs#296]
Hello guys,

I am using hubspot client 8.3.1 for NodeJS 16.

When I try to get a list of user or create an user using the pure client:

`hubspot_client.crm.contacts.searchApi.doSearch("some params")`

I get this issue, in AWS Lambda cannot find module ../discovery/crm/CrmDiscovery

If I switch to use the apiRequest option:

```
hubspot_client.apiRequest({
        method: 'POST',
        path: '/crm/v3/objects/contacts',
        body: contact_params
})
```

I encounter absolutely no issue.

Another odd happening is that I can use either way if I run on my local machine, but as soon as it's on an AWS Lambda, it just can't find the module.
Yes the hubspot client is installed in the AWS lambda before you ask :-)

If any one knows why this is happening, would be good to know. Could it be a limitation of hubspot client in AWS Lambda ? I am running Node 16 locally and in the lambda.

Thanks !

**Comment by alexleonov-tactiq** [comment]
I'm having the same issue with anything 8.x.x. We're building using esbuild, and I think there is an issue in module resolution when the require's don't have the extension at the end. Perhaps, AWS Lambda is using similar bundler and runs into the same issue.

For a few other packages, I've manually added yarn patches to add .js extensions, but for @hubspot/api-client there are too many places.

I'm pretty sure the problem will be gone if the generated .js files in the library will have imports with file extensions.

**Comment by krymtkts** [comment]
Is this problem caused by this change?
[Release Regenerate all clients (Breaking Changes) · HubSpot/hubspot-api-nodejs](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.0.0)

I am using version 7.1.2 with AWS Lambda built with AWS CDK and it works fine.
However, when I bumped it to version 8.4.0 to use the retry mechanism, the same problem occurred.

**Comment by zhex900** [comment]
I have the same issue!

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've fixed it.
Could you check [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/8.4.1), please?

**Comment by krymtkts** [comment]
I tried version 8.4.1 with AWS Lambda built with AWS CDK and got the same error.

**Comment by Chris59160** [comment]
I can confirm on my side, that
client.crm.contacts.searchApi.doSearch(request)
client.crm.contacts.basicApi.create(contactObject)

both works as of 8.40 within a Lambda environment running on Node 16

**Comment by serhii-kucherenko** [comment]
Still the problem:(

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've fixed it.
Could you check [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/8.4.2), please?

**Comment by krymtkts** [comment]
I tested version 8.4.2 and it works fine. Thanks!
