### ISSUE TITLE
CRM Engagements Communications

### ISSUE THREAD

**Issue by thurdev** [HubSpot/hubspot-api-nodejs#297]
Correct if I'm wrong, but I wasn't able to find https://developers.hubspot.com/docs/api/crm/communications in this repo.

I suppose because its a new thing from HB.

Or is that anywhere here?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
I've just added CRM Engagements Communications in [9.0.0-beta.1 version](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.1).

`hubspot.crm.objects.communications`
