### ISSUE TITLE
node search deal api return all deals. 

### ISSUE THREAD

**Issue by BatunaAz** [HubSpot/hubspot-api-nodejs#302]
const filter = { propertyName: 'name', operator: 'EQ', value: `OSUG /BU/` }
    const filterGroup = { filters: [filter] }
    const sort = JSON.stringify({ propertyName: 'cp_tenant_name', direction: 'DESCENDING' })
    const query = 'name'
    const properties = ['name', 'id']
    const limit = 1
    const after = 0
    
    const publicObjectSearchRequest = {
        filterGroups: [filterGroup],
        sorts: [sort],
        query,
        properties,
        limit,
        after,
    }
    console.log(`hey: ${JSON.stringify(publicObjectSearchRequest)}`)
    const reply = await hubspotClient.crm.deals.searchApi.doSearch({
        publicObjectSearchRequest});
    console.log(`DEAL BY TENANT: ${JSON.stringify(reply)}`);
  }
  
  Why it returned all deals. IT could not query by my passed filter

**Comment by ksvirkou-hubspot** [comment]
Hi @BatunaAz .
Workable example:
```javascript
const filter = { propertyName: 'dealname', operator: 'EQ', value: 'Caling' }
const filterGroup = { filters: [filter] }
const sort = JSON.stringify({ propertyName: 'cp_tenant_name', direction: 'DESCENDING' })
const properties = ['dealname', 'id']
const limit = 1
const after = 0

const publicObjectSearchRequest = {
    filterGroups: [filterGroup],
    sorts: [sort],
    properties,
    limit,
    after,
}

console.log(`hey: ${JSON.stringify(publicObjectSearchRequest)}`)
const reply = await hubspotClient.crm.deals.searchApi.doSearch(publicObjectSearchRequest);
console.log(`DEAL BY TENANT: ${JSON.stringify(reply)}`);
```
