### ISSUE TITLE
Bug:  hubspotClient.cms.hubdb.rowsApi.getTableRows Can not take more than one properties

### ISSUE THREAD

**Issue by iqoOopi** [HubSpot/hubspot-api-nodejs#303]
1. First issue, your current [documentation ](https://developers.hubspot.com/docs/api/cms/hubdb)needs to be updated as there are no **tables.rowsApi**.  According to the ts file, the 'rowsApi' has been moved directly under "hubdb", so it's **hubdb.rowsApi** instead of **hubdb.tables.rowsApi**
![image](https://user-images.githubusercontent.com/46897552/212200950-23dbc5d9-540c-42b0-9d11-3eda7fc4df02.png)

2. The second issue is actually a **bug**:
I'm using the newest SDK to get table rows, when I pass 2 column names to the properties, it returns an empty values object
![image](https://user-images.githubusercontent.com/46897552/212201245-7145987a-a5e7-4043-8599-7d4623e9e75e.png)
![image](https://user-images.githubusercontent.com/46897552/212201509-e04bbed4-6e65-4423-a1ca-8ee9a9d16ad4.png)

However, if I pass only one column name at a time, they all can return back values:
![image](https://user-images.githubusercontent.com/46897552/212201667-635e0d63-8b04-4129-bb01-5422839ad294.png)
![image](https://user-images.githubusercontent.com/46897552/212201778-1d0b1a0a-69d7-4fd0-aaaf-83bc8f7a73bc.png)

So seems like properties do not like an array of strings?

PS: I checked the source code of the SDK file, looks like the query param is being set correctly for properties from the requestFactory. Maybe the issue is from your backend code, looks like it does not parse query param correctly for properties

**Comment by ksvirkou-hubspot** [comment]
Hi @iqoOopi .
Thank you for reporting this issue.
1) I've just fixed it.
2) It is a bug. I'm investigating it.

**Comment by iqoOopi** [comment]
Thanks, Ksvirkou,

Found another documentation issue https://developers.hubspot.com/docs/api/cms/hubdb,  it is missing the inputs body, I guessed it out, should need "Id" and "values"
![image](https://user-images.githubusercontent.com/46897552/212717732-cc8a1a3b-35bc-4eec-a0a3-b99a42e1d25c.png)

**Comment by iqoOopi** [comment]
@ksvirkou-hubspot  Also I'm wondering what should I pass in to populate a single select type column. The documentation only has examples for multi select, I tried {id:"1"} which does not work.
![image](https://user-images.githubusercontent.com/46897552/212749553-d6ca8c47-4971-4e48-818c-a8e2f52a8086.png)

**Comment by iqoOopi** [comment]
@ksvirkou-hubspot I Just found another one, which should be "_form" instead of "form" per the ts file, passing in "form" will receive a missing required variable error. Looks like a typo passed your QA and entered Prod. 
![image](https://user-images.githubusercontent.com/46897552/213817938-0ca03a45-9046-4fa1-9d5a-06a2906b9540.png)

**Comment by ksvirkou-hubspot** [comment]
> @ksvirkou-hubspot I Just found another one for this [documentation](https://developers.hubspot.com/docs/api/crm/associations/v3), which should be "**_from**" instead of "**from**" per the ts file, passing in "**from**" will receive a missing required variable error. Looks like a typo passed your QA and entered Prod. ![image](https://user-images.githubusercontent.com/46897552/213817938-0ca03a45-9046-4fa1-9d5a-06a2906b9540.png)

https://github.com/HubSpot/hubspot-api-nodejs/issues/171

**Comment by ksvirkou-hubspot** [comment]
Hey @iqoOopi .
The second bug have been fixed.
I mean ` when I pass 2 column names to the properties, it returns an empty values object`.

**Comment by ksvirkou-hubspot** [comment]
> Also I'm wondering what should I pass in to populate a single select type column. The documentation only has examples for multi-select, For single-select I tried {id:"1"} and just "1", but none of them worked.

Workable example:
```javascript
const request = { 
        values: {
            "select": {
                "id":"2",
                "name":"opt2",
                "type":"option",
                "order":2
            }
        }
    };

    const response = await hubspotClient.cms.hubdb.rowsApi.updateDraftTableRow(
        'table',
        'rowId',
        request
    );

    console.log(response)
```

**Comment by ksvirkou-hubspot** [comment]
> Thanks, Ksvirkou,
> 
> Found another documentation issue https://developers.hubspot.com/docs/api/cms/hubdb, it is missing the inputs body, I guessed it out, should need "Id" and "values" ![image](https://user-images.githubusercontent.com/46897552/212717732-cc8a1a3b-35bc-4eec-a0a3-b99a42e1d25c.png)

We have fixed it.
