### ISSUE TITLE
CollectionResponsePublicAssociationDefiniton - Definiton is a typo

### ISSUE THREAD

**Issue by ExpliuM** [HubSpot/hubspot-api-nodejs#304]
[CollectionResponsePublicAssociationDefiniton.ts](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/associations/models/CollectionResponsePublicAssociationDefiniton.ts
)

`CollectionResponsePublicAssociationDefiniton` - Definiton is a typo

**Comment by ksvirkou-hubspot** [comment]
Hi @ExpliuM .
Thank you for reporting the issue.
I've fixed it in [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.4.0).
