### ISSUE TITLE
Unable to associate contact with ticket

### ISSUE THREAD

**Issue by joshuabaker** [HubSpot/hubspot-api-nodejs#307]
Request validation is failing when trying to create an association between tickets and contacts using the associations API.

**Request**

```js
await hubspotClient.crm.tickets.associationsApi.create(
  parseInt(ticket.id),
  "contacts",
  parseInt(contact.id),
  "ticket_to_contact"
);
```

**Response Error**

```json
{
  "status": "error",
  "message": "Invalid input JSON on line 1, column 3. Some required fields were not set: [associationCategory, associationTypeId]",
  "correlationId": "67dd8653-80b4-4c05-be62-008816d6d75a",
  "category": "VALIDATION_ERROR"
}
```

Version: 8.4.0

Possible regression of #273.

**Comment by joshuabaker** [comment]
Passing the ID of the association as an integer works, but is flagged by the TS highlighter as incorrect.

```
Argument type number is not assignable to parameter type Array<AssociationSpec>
```

Should this now also accept a string value?

**Comment by ksvirkou-hubspot** [comment]
Hi @joshuabaker .
You need pass Array<AssociationSpec>.
Here are the workable examples:
with AssociationSpec
```javascript
const response = await hubspotClient.crm.tickets.associationsApi.create(
        '1378645006',
        'contacts',
        '307753',
        [
            {
              "associationCategory": "HUBSPOT_DEFINED",
              "associationTypeId": 16
            }
        ]
    );
```
without AssociationSpec
```javascript
const response = await hubspotClient.crm.tickets.associationsApi.create(
        '1378645006',
        'contacts',
        '307753',
        []
    );
```

**Comment by joshuabaker** [comment]
It feels like the default association types should be constants or strings for a better DX (e.g. `TICKET_TO_CONTACT_ASSOCIATION_TYPE`). This would actually lead to smaller bundle sizes too.

N.B. The readme currently still references string values for this.

https://github.com/HubSpot/hubspot-api-nodejs/blob/eba1b395084623b41da20b9cf7cb538419ab9c85/README.md?plain=1#L117-L122

**Comment by ksvirkou-hubspot** [comment]
I've update README.
Hubspot created for it endpoint because now users can manage association's types.
`GET https://api.hubapi.com/crm/v4/associations/tickets/contacts/labels`
More information you can find in [the docs](https://developers.hubspot.com/docs/api/crm/associations).

**Comment by joshuabaker** [comment]
Unless I’m mistaken, you cannot erase the HubSpot defined associations though, right?

**Comment by ksvirkou-hubspot** [comment]
I have no information about it. 
It is in Alfa now. 
When we have this information we will take a decision.

**Comment by joshuabaker** [comment]
The creation of custom associations via the API is in alpha, but the ‘company to contact’, ‘ticket to contact’, etc. have been around for years. v3 was generally available in early 2020 and supported these without issue.

All I’m saying is that you should provide constants for the HubSpot-defined associations for an improved developer experience and better code readability.

**Comment by ksvirkou-hubspot** [comment]
Hey @joshuabaker .
I've added enum `AssociationTypes`.
You find it in [the latest version](https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/8.5.0).

**Comment by joshuabaker** [comment]
Thanks, @ksvirkou-hubspot. That looks great. 🙏🏻
