### ISSUE TITLE
Go SDK + Building CloudQuery source plugin.

### ISSUE THREAD

**Issue by yevgenypats** [HubSpot/hubspot-api-nodejs#308]
Hi team, hopefully this is right place to ask, if not would appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. Our users are interested in a hubspot plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview) and you will help maintain it. This will give your users the ability to sync HubSpot data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by ksvirkou-hubspot** [comment]
@atanasiuk-hubspot

**Comment by atanasiuk-hubspot** [comment]
Hi @yevgenypats, thanks for bringing this up, we passed the request to the leadership team, will keep you posted. Closing this for now
