### ISSUE TITLE
hubspotClient.apiRequest to "/filemanager/api/v3/files/upload" Unsupported Media Type for docx files using Private App.

### ISSUE THREAD

**Issue by luriya1** [HubSpot/hubspot-api-nodejs#319]
const hubspot = require("@hubspot/api-client")

formData.append("folderPath", "/")
        formData.append("options", JSON.stringify(options))
        formData.append("file", fs.createReadStream(`Thank You Page.docx`))
        console.log(formData)

        const hubspotFileUpload = await hubspotClient.apiRequest({
            method: "POST",
            path: "/filemanager/api/v3/files/upload",
            body: formData,
            
            defaultJson: false,
            
        })

Why is this returning me a 415 error?

**Comment by luriya1** [comment]
Is this api deprectated?

**Comment by ksvirkou-hubspot** [comment]
Hi @luriya1 .
I can't reproduce it. 
Workable example 
```Javascript
  const formData = new FormData();
  const options = {
    access: "PUBLIC_NOT_INDEXABLE",
    overwrite: false,
    duplicateValidationStrategy: "NONE",
    duplicateValidationScope: "EXACT_FOLDER"
  };
  formData.append("folderPath", '/');
  formData.append("options", JSON.stringify(options));
  formData.append("file", fs.createReadStream('./file.docx'));

  const fileUploadReq = await hubspotClient.apiRequest({
      method: 'POST',
      path: '/filemanager/api/v3/files/upload',
      body: formData,
      defaultJson: false
  });

  console.log(fileUploadReq);
```
