### ISSUE TITLE
[Bug] "Error: Cannot parse content. No Content-Type defined." on calling "archiveRefreshToken"

### ISSUE THREAD

**Issue by marlokessler** [HubSpot/hubspot-api-nodejs#320]
## Bug
When calling `hubSpot.oauth.refreshTokensApi.archiveRefreshToken(refreshToken)` the following error is thrown: `Error: Cannot parse content. No Content-Type defined.` IMHO this is because the endpoint returns a `HTTP 204 - No Content` but the client tries to parse an answer (which does not exist, since no content).

## Environment
- Node version: 16
- Package: "@hubspot/api-client": "^8.4.1"

**Comment by ksvirkou-hubspot** [comment]
Hi @marlokessler .
I've just fixed it in [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/8.6.0).

**Comment by marlokessler** [comment]
Thank you!
