### ISSUE TITLE
Cannot update object to set non-required property to `null`

### ISSUE THREAD

**Issue by rcbevans** [HubSpot/hubspot-api-nodejs#324]
`hs_next_step` is not a required property on a `Deal`.

After creating a new `Deal` in HubSpot the `hs_next_step` is `null`.

Calling `deal.basicApi.update` with a properties payload of `{ hs_next_step: null }` results in a successful response, but the value of `hs_next_step` is not cleared.

In the type definitions of the sdk I see `SimplePublicObjectInput` is defined as `{ properties: Record<string, string> }` which does mean that me passing null is a violation of this contract, but how else can I set a nullable property to null?

**Comment by ksvirkou-hubspot** [comment]
Hi @rcbevans .
You can set empty string for it (`"property": ""`).

**Comment by ksvirkou-hubspot** [comment]
_Clearing properties_
_You can clear an object property value via the API by setting the property value to an empty string._

_Example: To clear the firstname from a contact object, send a PATCH request to `https://api.hubapi.com/crm/v3/objects/contacts/{contactId}` with the body `{ "properties": { "firstname": ""} }`._
https://developers.hubspot.com/docs/api/crm/understanding-the-crm
