### ISSUE TITLE
v3.2.0 is missing the lib folder

### ISSUE THREAD

**Issue by codecadwallader** [HubSpot/hubspot-api-nodejs#33]
I was just getting started with this API and when I installed the latest (v3.2.0 published an hour ago) the `lib` folder did not appear to exist at all.  Downgrading to v3.1.0 seems to resolve the issue for me.

**Comment by atanasiuk-hubspot** [comment]
Hi, @codecadwallader, thank you for reporting this! 
This should be fixed in the [latest](https://www.npmjs.com/package/@hubspot/api-client/v/3.2.5) npm release. Feel free to upgrade.

**Comment by codecadwallader** [comment]
Thanks @atanasiuk-hubspot .. I can confirm it appears resolved for me in v3.2.5.  Thanks for the quick turnaround!
