### ISSUE TITLE
audit-logs API is not available 

### ISSUE THREAD

**Issue by rahman973** [HubSpot/hubspot-api-nodejs#330]
`await hubspotClient.cms.auditLogs.defaultApi.getPage()`

in  hubspotClient.cms class there is not auditlogs function? please check it

https://github.com/HubSpot/hubspot-api-nodejs#get-audit-logs

**Comment by ksvirkou-hubspot** [comment]
Hi @rahman973 .
I've just updated [readme](https://github.com/HubSpot/hubspot-api-nodejs#get-audit-logs).
Workable example:
```javascript
const response = await hubspotClient.cms.auditLogs.auditLogsApi.getPage()
```
