### ISSUE TITLE
Property 'body' does not exist on type 'SimplePublicObjectWithAssociations'

### ISSUE THREAD

**Issue by sakhmedbayev** [HubSpot/hubspot-api-nodejs#336]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/8005396/221982070-275abab8-2348-4348-9ea5-01eee83ccee6.png">

**Comment by ksvirkou-hubspot** [comment]
Hi @sakhmedbayev .
This property doesn't support from 6.0.x version or later.
I'll fix the docs as soon as possible.
Workable example:
```javascript
  const contact = await hubspotClient.crm.contacts.basicApi.getById(contactId, properties, propertiesWithHistory, associations, archived);
  return contact;
```

**Comment by ksvirkou-hubspot** [comment]
I've just fixed the docs.
