### ISSUE TITLE
9.0.0-beta.3 associationsApi

### ISSUE THREAD

**Issue by juansss** [HubSpot/hubspot-api-nodejs#373]
Hi!

I'm using the new beta with associationsApi but i'm getting this error

`await hubspotClient.crm.contacts.associationsApi.create(`

`Property 'associationsApi' does not exist on type 'ContactsDiscovery'.ts(2339)`

The same with companies

`Property 'associationsApi' does not exist on type 'CompaniesDiscovery'.ts(2339)`

Do i missing something?

Thanks

**Comment by ksvirkou-hubspot** [comment]
Hi @juansss .
These APIs [were removed](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/CHANGELOG.md#updated-2).
I recommend you use `hubspot.crm.associations.v4.basicApi.create()`.
