### ISSUE TITLE
AssociationTypes is not defined when trying the contact and company example

### ISSUE THREAD

**Issue by Novam-IT** [HubSpot/hubspot-api-nodejs#378]
Hi,

When I'm trying the create a contact and company example, it won't create the association. It returns AssociationTypes is not defined as an error.

` "associationTypeId": AssociationTypes.companyToContact //This gives the error`

**Comment by ksvirkou-hubspot** [comment]
Hi @Novam-IT 
What version of the SDK do you use?

**Comment by ksvirkou-hubspot** [comment]
You need to import AssociationTypes to your script.
Workable example (In case of using `require` function):
```javascript
const hubspot = require('@hubspot/api-client')
hubspot.AssociationTypes.companyToContact;
```
Workable example (In case of using `import`):
```javascript
import AssociationTypes from 'pathToSDK/enums/AssociationTypes'
AssociationTypes.companyToContact;
```
