### ISSUE TITLE
API doesn't work with Webpack 5, Node 18

### ISSUE THREAD

**Issue by HugDoggyDogg** [HubSpot/hubspot-api-nodejs#380]
Hello,

I've been trying to use the NodeJS api for Hubspot on my GatsbyJS website.

First thing, the gatsby client directly crashes on start with the error:
`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.`
This error is displayed for several modules: `querystring`, `crypto`, then `stream`. So I included polyfills in my webpack config. I have tried with a library specifically designed for that:

```javascript
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

exports.onCreateWebpackConfig = ({
                                     actions,
                                 }) => {
    actions.setWebpackConfig({
        plugins: [
            new NodePolyfillPlugin({
                includeAliases: ['crypto', 'querystring', 'stream'],
            }),
        ],
    })
}
```
I also tried with individual polyfills:

```javascript
exports.onCreateWebpackConfig = ({
                                     actions,
                                 }) => {
    actions.setWebpackConfig({
        resolve: {
            fallback: {
                "querystring": require.resolve("querystring-es3"),
                "crypto": require.resolve("crypto-browserify"),
                "stream": require.resolve("stream-browserify"),
            },
        },
    })
}
```

And with both methods the app runs.

### Why I am stuck

However, when I try to fetch some objects (i.e. the Owners), the request do not succeed and I get this error:
`TypeError: url_1.URL is not a constructor` (see complete screenshot below)

I tried to fix it using the same method with polyfills but without any success:
```javascript
 "url": require.resolve("url/"),
 // OR:
  "url": require.resolve("url"),
  // OR
  const { Url } = resolve("url").Url;
  "url": Url,
```

I have considered using direct API calls, but it can't be done by front-end only as the requests are blocked by CORS policies. Using a backend proxy to be able to connect with Hubspot sounds like much trouble while the Node api seemed great.

My environment is Node 18.15.0, npm 9.6.5. I am unable to downgrade because Gatsby v5 requires Node 18+.

### Reproducible example

I have reproduced the error in minimal project conditions by doing the following steps:
- Create a fresh gatsby site with `npm init gatsby`. Using Typescript, no CMS, no styling system or other plugins.
- `npm install @hubspot/api-client`
- `npm install node-polyfill-webpack-plugin`
- Create a custom hook that instantiates the Client plugin with the accessToken and tries to fetch with:
```javascript
import {useEffect, useState} from "react";

import { Client } from "@hubspot/api-client";
const hubspotClient = new Client({ accessToken: 'XXXXX' });

interface UseHubspotType {}

function useHubspot(): UseHubspotType {
    const [salesmen, setSalesmen] = useState<any[]>([]);

    const fetchHubspotSalesmen = () => {
        hubspotClient.crm.owners.ownersApi.getPage(
            undefined,
            undefined,
            100,
        ).then(res => {
            console.log({res});
        })
            .catch(err => {
                console.log({err});
            });
    };

    useEffect(() => {
        fetchHubspotSalesmen();
    }, []);


    return {};
}

export default useHubspot;
```
- Create a `gatsby-node.js` file at the project root to customize the webpack config:
```javascript
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

exports.onCreateWebpackConfig = ({
                                     actions,
                                 }) => {
    actions.setWebpackConfig({
        plugins: [
            new NodePolyfillPlugin({
                includeAliases: ['crypto', 'querystring', 'stream'],
            }),
        ],
    })
}
```
- Call the hook in `index.tsx`: `const hubspot = useHubspot();`
- Start the app with `npm start`
- Watch the console for the error to show up.
![image](https://github.com/HubSpot/hubspot-api-nodejs/assets/47081772/1be67878-10d9-4c5d-89da-33a53c591d48)

So, can someone suggest the next steps to make the Node api work please ? It would be much appreciated 🙏

**Comment by berkatik** [comment]
I am also having the save problem with Node14 in Vue2 application.

**Comment by berkatik** [comment]
Fixed the issue by moving integration to server-side. Looks like hubspot api is not able to work on browser.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
This SDK is created only for back end development (node js).
