### ISSUE TITLE
Setting associations for deals on create not working

### ISSUE THREAD

**Issue by eidermaen** [HubSpot/hubspot-api-nodejs#382]
**Notice: This might not be related to the sdk but to the REST API itself**

I'm trying to create a new deal and link it to an existing contact by executing `client.crm.deals.basicApi.create(data)` where data is
```js
{
  "properties": {
    "pipeline": "default",
    "dealname": "dealname",
    "dealstage": "contractsent",
  },
  "associations": [
    {
      "to": {
        "id": "some-id"
      },
      "types": [
        {
          "associationCategory": "HUBSPOT_DEFINED",
          "associationTypeId": 3
        }
      ]
    }
  ]
}
```

The deal is created successfully (also no error is thrown saying that the association did not work etc.). The association, however, is not created. When using the REST API (`POST https://api.hubapi.com/crm/v4/objects/deals/`) I get the same result.

Linking both entries afterwards works so linking in general is working without any issues.

Any idea why it isn't working using the sdk/ REST API?

Cheers

**Comment by ksvirkou-hubspot** [comment]
Hi @eidermaen .
What version of the SDK do you use?
`associations` property was added to the client in [9.0.0-beta.0](https://www.npmjs.com/package/@hubspot/api-client/v/9.0.0-beta.0) .

**Comment by eidermaen** [comment]
Hi @ksvirkou-hubspot,
thanks for the hint. You're right, I'm on `"@hubspot/api-client": "^8.9.0"`.
My current workaround was to 

1. create the deal entry
2. use the associations api (`client.crm.deals.associationsApi.create`) to create the association

Is this also the recommended way? Or is there a better one?

**Comment by eidermaen** [comment]
Never mind. Just updated the dependency and ran a quick check. Seems as if nothing broke by doing so. 
So I'll go with version 9.

Thanks!

**Comment by ksvirkou-hubspot** [comment]
Looks good, but I recommend you use another associations api (`client.crm.objects.associationsApi.create`), instead of `client.crm.deals.associationsApi.create` because this api was removed from the latest version of the SDK.

**Comment by ksvirkou-hubspot** [comment]
> Hi @ksvirkou-hubspot, thanks for the hint. You're right, I'm on `"@hubspot/api-client": "^8.9.0"`. My current workaround was to
> 
> 1. create the deal entry
> 2. use the associations api (`client.crm.deals.associationsApi.create`) to create the association
> 
> Is this also the recommended way? Or is there a better one?

Looks good, but I recommend you use another associations api (`client.crm.objects.associationsApi.create`), instead of `client.crm.deals.associationsApi.create` because this api was removed from the latest version of the SDK.
