### ISSUE TITLE
No idea how to use the updated `SimplePublicObjectInputForCreate`

### ISSUE THREAD

**Issue by rcbevans** [HubSpot/hubspot-api-nodejs#383]
It looks like the ability to create to create associations when creating an object has been added in v9 of the node sdk, but I can't figure out how the api should be used.

Are there any code examples, or documentation anywhere?

The [web API](https://developers.hubspot.com/docs/api/crm/contacts) documentation doesn't demonstrate how to insert with associations as no "complete" examples are given, and clicking add test value in the swagger interface doesn't insert any test values.

**Comment by ksvirkou-hubspot** [comment]
Hi @rcbevans 
You can create almost all objects with associations, except contacts.
[The contacts docs page ](https://developers.hubspot.com/docs/api/crm/contacts#create-contacts)says: "you cannot create a contact and associate it with a record or activity in the same request." 
But ability to create contacts with associations was added to the swagger file.
I asked Hubspot to fix it they either add ability to create contacts with associations or fix the swagger file.

**Comment by ksvirkou-hubspot** [comment]
Workable example (create company with association to contact) :
```javascript
   const SimplePublicObjectInputForCreate = {
    properties: {
      "city": "Cambridge",
      "domain": "biglytics.net",
      "industry": "Technology",
      "name": "Biglytics",
      "phone": "(877) 929-0687",
      "state": "Massachusetts"
    },
    associations: [
      {
        "to": {
          "id": "309960"
        },
        "types":[
          {
            "associationCategory":"HUBSPOT_DEFINED",
            "associationTypeId": 2
          }
        ]
      }
    ]
  };

  const apiResponse = await hubspotClient.crm.companies.basicApi.create(SimplePublicObjectInputForCreate);
```
Version of the SDK is 9.0.0.

**Comment by rcbevans** [comment]
Thanks for the example. Would be great if the documentation had some such working examples to demo's not how the sdk can be used, parameter types etc.

I'll close the issue.
