### ISSUE TITLE
Are CRM object IDs numbers or strings?

### ISSUE THREAD

**Issue by stevekanter** [HubSpot/hubspot-api-nodejs#393]
It seems unclear if CRM objects (Deal, Contact, Company, at least) have string IDs or number IDs.

Even the README in this repo is not correct https://github.com/HubSpot/hubspot-api-nodejs#example-create-contact-company-and-associate-created-objects

It says to use the `id` of `hubspotClient.crm.contacts.basicApi.create` and pass that into `hubspotClient.crm.associations.v4.basicApi.create`. However, the former returns a TypeScript type that has [`id` typed as a string](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/contacts/models/SimplePublicObject.ts#L30) and the latter [wants a number](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/associations/v4/types/PromiseAPI.ts#L51).

Which is it? Until this gets resolved, I either have to cast my types or I need to use `parseInt` on the string being returned from the creation call. Both feel icky.

**Comment by stevekanter** [comment]
I just checked the [API Docs](https://developers.hubspot.com/docs/api/crm/associations) (which I can't directly link to because the docs don't deep link, another pet peeve) and it implies that the ID gets passed in as a path parameter but wants an integer. Technically speaking, integers can get coerced into a string, but if we're being strictly accurate, it sounds like the v4 association API is incorrect and it should be labeled as a `string`.

<img width="136" alt="image" src="https://github.com/HubSpot/hubspot-api-nodejs/assets/33847555/8fa4c4e0-be08-402e-9b13-03b81bf5e52f">

**Comment by ksvirkou-hubspot** [comment]
Hi @stevekanter .
It is a bug.
The SDK is auto-generated based on swagger files.
I have made request for fixing it.
When it is fixed, I'll regenerate the SDK.

**Comment by tshma-lex** [comment]
@ksvirkou-hubspot any updates about this issue? In v 10.2.0 it's still typed as number

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
It have been fixed in the latest version of the SDK([11.0.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.0.0))
