### ISSUE TITLE
Interface error on TimelineEventTemplateToken, options field must be required only if type === enumeration

### ISSUE THREAD

**Issue by spike008t** [HubSpot/hubspot-api-nodejs#394]
Hello,

Small issue with `TimelineEventTemplateToken` model with typescript.
The `options` field is mandatory when it should be optional if type != `enumeration`

https://github.com/HubSpot/hubspot-api-nodejs/blob/918a11c82924a23a445bfc0b6ae9b85a4a418f43/codegen/crm/timeline/models/TimelineEventTemplateToken.ts#L31

**Comment by ksvirkou-hubspot** [comment]
Hi @spike008t .
Thank you for reporting the issue.
It have been fixed it in [version 10.0.0](https://www.npmjs.com/package/@hubspot/api-client/v/10.0.0) .
