### ISSUE TITLE
[BUG] Wrong type for HubDbTableRowV3BatchUpdateRequest 'id' property, should be string instead of number

### ISSUE THREAD

**Issue by iqoOopi** [HubSpot/hubspot-api-nodejs#398]
I'm on @hubspot/api-client": "^9.1.0",

![image](https://github.com/HubSpot/hubspot-api-nodejs/assets/46897552/9ef2f9a7-0f35-4c85-a6ba-c0e1c7b43184)
![image](https://github.com/HubSpot/hubspot-api-nodejs/assets/46897552/4e319154-4c64-4fdd-8548-b5bc121b2764)

per the API document, the 'id' should be string type not number. In fact, all the get endpoints are returning id as a string.

**Comment by ksvirkou-hubspot** [comment]
Hi @iqoOopi .
Thank you for reporting this issue
It have been fixed it in [version 10.0.0](https://www.npmjs.com/package/@hubspot/api-client/v/10.0.0) .
