### ISSUE TITLE
Missing Notes endpoint

### ISSUE THREAD

**Issue by leobaldoneto** [HubSpot/hubspot-api-nodejs#413]
Hi, the client is missing notes engament endpoint.

I tried to use apiRequest method and parsing the response but it is getting invalid json error.

```
    const response = await hubspot.apiRequest({
      method: 'GET',
      path: '/crm/v3/objects/notes/'+dealId,
      qs: {
        properties: 'hs_timestamp,hs_note_body',
        associations: 'deals',
      }
    });
    const parsedResponse = await response.json();
    console.log(parsedResponse);
```

The error:
`
FetchError {message: 'invalid json response body at https://api.hu…on: Unexpected token < in JSON at position 0', type: 'invalid-json', stack: 'FetchError: invalid json response body at
`

**Comment by leobaldoneto** [comment]
The error was because an 404 error.

**Comment by ksvirkou-hubspot** [comment]
Hi @leobaldoneto .
It is better to use  note client.
```javascript
const note = hubspot.crm.objects.notes.basicApi.getById(noteId);
```

**Comment by leobaldoneto** [comment]
I thought it was not implemented. I will try it again, thank you for the fast response.
