### ISSUE TITLE
Question | How to get all notes for a specific deal with the info (property) which deal is pinned

### ISSUE THREAD

**Issue by natterstefan** [HubSpot/hubspot-api-nodejs#414]
Dear maintainers and contributors,

can you please share an example for the use case as per the issue title?

Thank you very much for your time and help.

**Comment by natterstefan** [comment]
Hi @ksvirkou-hubspot,

thanks for sharing a workable example. Very kind of you. What about this request in the issue title "with the info (property) which deal is pinned"? Is this possible? How can I filter by pinned notes? They are valuable in the UI on Hubspot, but I see no way of getting them per API...

**Comment by ksvirkou-hubspot** [comment]
In Hubspot you can associate objects and  associated objects have no pinned property.
You can read more in[ the docs](https://developers.hubspot.com/docs/api/crm/associations).

**Comment by ksvirkou-hubspot** [comment]
For filtering by associated notes you can use method `hubspotClient.crm.objects.notes.searchApi.doSearch(request)`.
You can read more in [Search docs](https://developers.hubspot.com/docs/api/crm/search) and [Notes docs](https://developers.hubspot.com/docs/api/crm/notes).
Workable example:
```javascript
async function main() {
  let deal = await hubspotClient.crm.deals.basicApi.getById('14355896864', undefined, undefined, ['notes']);
  console.log(deal.associations?.notes?.results)

  if (deal.associations?.notes != undefined) {
    let associatedNotes = [];
    for(const association of deal.associations?.notes.results) {
      console.log(association.id)
      associatedNotes.push(association.id)
    }
    const request = {
      properties: ["hs_body_preview"],
      filterGroups: [
        {
          filters:[
            {
              propertyName: "id",
              values: associatedNotes,
              operator: "IN"
            },
            {
              propertyName: "hs_body_preview",
              value: "Note1",
              operator: "EQ"
            }
          ]
        }
      ]
    };
    const notes = await hubspotClient.crm.objects.notes.searchApi.doSearch(request);
    console.log(notes);
  }
}
```

**Comment by natterstefan** [comment]
Hi @ksvirkou-hubspot,

that is correct and works, but I am asking how I can get the pinned note of an entity:

- https://community.hubspot.com/t5/Releases-and-Updates/Pinned-Notes-in-HubSpot-CRM/ba-p/418184
- https://knowledge.hubspot.com/contacts/pin-a-note-in-a-record

**Comment by ksvirkou-hubspot** [comment]
Hi @natterstefan . 
You can get pinned object id by this way:
```javascript
 let deal = await hubspotClient.crm.deals.basicApi.getById('14355896864', ['hs_pinned_engagement_id']);

  if (deal.properties.hs_pinned_engagement_id != undefined) {
    llet note = await hubspotClient.crm.objects.notes.basicApi.getById(deal.properties.hs_pinned_engagement_id);
    console.log(note)
  }
```
if you don't know type of pinned id you can get it by this way:
```javascript
 let deal = await hubspotClient.crm.deals.basicApi.getById('14355896864', ['hs_pinned_engagement_id'], undefined, ['notes']);
  console.log(deal)

  if (deal.properties.hs_pinned_engagement_id != undefined) {
    let engagement = await hubspotClient.crm.objects.basicApi.getById('engagement', deal.properties.hs_pinned_engagement_id, ['hs_engagement_type']);
    console.log(engagement)
  }
```
