### ISSUE TITLE
Can `associations` in creation request be optional?

### ISSUE THREAD

**Issue by bigen1925** [HubSpot/hubspot-api-nodejs#422]
Hi there,

Thank you all for developing and maintaining this great library!
It makes us joyful to use Hubspot. :D

I feel happy that we can associate objects with `associations` interface when create other objects.
It is so smart and readable.

On the other hand, in most cases I create objects without associations.
Then I need write `associations: []` every time like 
```ts
await hubspot.crm.contacts.basicApi.create({
    properties,
    associations: [], // without associations
})
```
, because it is required.

How about to make `associations` optional?

**Comment by shjacobs303** [comment]
Either this or update the documentation, though preferrably change associations to optional.

**Comment by ksvirkou-hubspot** [comment]
Hi everyone
The `associations` property have been made optional in [the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.1).
