### ISSUE TITLE
Functions API is missing the POST_ACTION_EXECUTION on type definition

### ISSUE THREAD

**Issue by ceifa** [HubSpot/hubspot-api-nodejs#426]
This leads to a type error, even when working

**Comment by ksvirkou-hubspot** [comment]
Hi @ceifa .
It've been fixed in the latest version([11.0.0-beta.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.0.0-beta.0)).

**Comment by ksvirkou-hubspot** [comment]
It've been fixed in the latest stable version([11.0.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.0.0)).
