### ISSUE TITLE
Automation functions API createOrReplaceByFunctionType doesn't works

### ISSUE THREAD

**Issue by ceifa** [HubSpot/hubspot-api-nodejs#427]
Just gives the error "Error: None of the given media types are supported: text/plain"

**Comment by ksvirkou-hubspot** [comment]
Hi @ceifa .
I think it've been fixed in the latest version([11.0.0-beta.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.0.0-beta.0)).

**Comment by ksvirkou-hubspot** [comment]
I've just fixed it in [10.2.1](https://www.npmjs.com/package/@hubspot/api-client/v/10.2.1).
I've checked it and it works correctly in [11.0.0-beta.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.0.0-beta.0) and higher.
