### ISSUE TITLE
Unable to be authorized while using sdk with accessToken

### ISSUE THREAD

**Issue by keremdokumaci** [HubSpot/hubspot-api-nodejs#432]
Hello,

I have been working with hubspot since a year. The sample successful request is in below that I have been using for long time.

`curl --location 'https://api.hubapi.com/crm/v3/objects/contacts?limit=100' \
--header 'Authorization: Bearer <pat-....>`

I am trying to use sdk for a new integration. However, I always receive the error below.

`{"body":{"category":"INVALID_AUTHENTICATION","correlationId":"f0ee980f-a446-4189-b004-ff06d08bf4e3","message":"Authentication credentials not found. This API supports OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview","status":"error"}`

Here is my implementation with sdk
`const hubspotClient = new Client({ accessToken: `Bearer <pat-....>`, numberOfApiCallRetries: 3, basePath:'https://api.hubapi.com' });
`

I have tried different versions of it. For example, apiKey instead of accessToken & pat without Bearer etc. None of them worked.

How can I authorize as before by using sdk?

**Comment by ksvirkou-hubspot** [comment]
Hi @keremdokumaci .
Workable example:
```javascript
import { Client } from "@hubspot/api-client";
const hubspotClient = new Client({ accessToken: "pat-..." });
```
Some API methods support only OAuth2 access token or only private app access token or only developer account API key.
You can check it in [the API docs](https://developers.hubspot.com/docs/api/overview).
For example [CRM timeline](https://developers.hubspot.com/docs/api/crm/timeline) methods.

**Comment by keremdokumaci** [comment]
> Hi @keremdokumaci . Workable example:
> 
> ```js
> import { Client } from "@hubspot/api-client";
> const hubspotClient = new Client({ accessToken: "pat-..." });
> ```
> 
> Some API methods support only OAuth2 access token or only private app access token or only developer account API key. You can check it in [the API docs](https://developers.hubspot.com/docs/api/overview). For example [CRM timeline](https://developers.hubspot.com/docs/api/crm/timeline) methods.

@ksvirkou-hubspot thanks for quick response. My issue is fixed. That was my mistake 😄
