### ISSUE TITLE
idProperty missing in SimplePublicObjectBatchInput.js model

### ISSUE THREAD

**Issue by IvoConversionCrew** [HubSpot/hubspot-api-nodejs#461]
In the SimplePublicObjectBatchInput.js model the **idProperty** is missing and is therefore stripped out of the request when setting this up. 

This is at least the case in:
- crm/objects/models/SimplePublicObjectBatchInput.js
- crm/companies/models/SimplePublicObjectBatchInput.js
- crm/contacts/models/SimplePublicObjectBatchInput.js

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
It have been fixed in the latest version of the SDK([11.1.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.1.0))
