### ISSUE TITLE
Undocumented breaking change for the searchApi parameter 'after'

### ISSUE THREAD

**Issue by klu2** [HubSpot/hubspot-api-nodejs#467]
The version 11.0.0 (https://github.com/HubSpot/hubspot-api-nodejs/releases/tag/11.0.0) changed some parameter types, but there is one not being mentioned.

`searchApi.doSearch` (i.e. on `crm.products.searchApi`) required a parameter `after` as a `number` before, now it's a `string`.  

Please adjust documentation (https://github.com/HubSpot/hubspot-api-nodejs?tab=readme-ov-file#example-search-contacts) accordingly and update the changelog

**Comment by ksvirkou-hubspot** [comment]
Hi @klu2.
This change was added and documented in [11.0.0-beta.0](https://github.com/HubSpot/hubspot-api-nodejs/blob/11.0.0/CHANGELOG.md?plain=1#L56).

**Comment by klu2** [comment]
Aha - I just opened the release page - probably it would be good to either refer to the changes of the beta.0 or include all changes in the official 11.0.0 release as well.

The documentation just says the type has changed, so where there was a number before (like `0`), it's now a string with the same content? (i.e. `'0'`)?

**Comment by ksvirkou-hubspot** [comment]
> Aha - I just opened the release page - probably it would be good to either refer to the changes of the beta.0 or include all changes in the official 11.0.0 release as well.
> 
> The documentation just says the type has changed, so where there was a number before (like `0`), it's now a string with the same content? (i.e. `'0'`)?

yes, it's now a string with the same content (i.e. `'0'`) or `after` from response.
