### ISSUE TITLE
BUG: hubspotClient.crm.lineItems.basicApi.create doesn't create associations

### ISSUE THREAD

**Issue by mcbergsma** [HubSpot/hubspot-api-nodejs#481]
Issue: Properly formed body creates the Line Item, but doesn't associate it with anything

Workaround: Use the raw api
```
hubspotClient.apiRequest({
      method: 'POST',
      path: '/crm/v3/objects/line_items',
      body: payload
    })
```

I've looked through the code and despite having the same version installed locally (11.1.0), it looks like it's using `SimplePublicObjectInput` which only has a `properties` property, no `associations` array. I tried to track this down in the code and it looks like it _should_ be using `SimplePublicObjectInputForCreate` which has to `associations` array.

**Comment by ksvirkou-hubspot** [comment]
Hi @mcbergsma 
The `associations` property became optional in [the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.1).
