### ISSUE TITLE
How read all notes of a deal?

### ISSUE THREAD

**Issue by realtebo** [HubSpot/hubspot-api-nodejs#483]
Using rest api I can do

    https://api.hubapi.com/crm/v3/objects/deals/:dealId/associations/notes?associations=deals&archived=false

Then, looping through results, I can retrieve a single note using

    https://api.hubapi.com/crm/v3/objects/notes/:noteId?properties=hs_note_body,hs_attachment_ids&archived=false

I can do the first call using this sdk, with 

```
    const deals = await hubspotClient.crm.deals.basicApi.getPage(
      dealsLimit,
      after,
      undefined,
      undefined,
      ["notes"]
    );
```

But how can I read all notes details of a single deal using this sdk?

**Comment by ksvirkou-hubspot** [comment]
Hi @realtebo 
You can get notes two ways: 

-  `GET crm/v3/objects/notes/:noteId`
```javascript
for (const associatedNote of dealResponse.associations.notes.results) {
    const noteResponse = await hubspotClient.crm.objects.notes.basicApi.getById(associatedNote.id, ['hs_note_body','hs_attachment_ids']);
    console.log(noteResponse)
  }
```
-  `POST crm/v3/objects/notes/batch/read`
```javascript
let notesIds = [];
for (const associatedNote of dealResponse.associations.notes.results) {
  notesIds.push({id: associatedNote.id})
}
const notesResponse = await hubspotClient.crm.objects.notes.batchApi.read({inputs: notesIds, properties: ['hs_note_body','hs_attachment_ids']});
console.log(notesResponse)
```
Version of the SDK - [11.1.0](https://www.npmjs.com/package/@hubspot/api-client/v/11.1.0)
