### ISSUE TITLE
All documentation for REST API calls is syntactically incorrect

### ISSUE THREAD

**Issue by siddheshranade** [HubSpot/hubspot-api-nodejs#486]
All the REST API examples that use the `@hubspot/api-client` npm package are wrong. For example, see the [custom objects page](https://developers.hubspot.com/docs/api/crm/crm-custom-objects) of the current documentation or even the [new beta documentation](https://developers.hubspot.com/beta-docs/reference/api/crm/objects/custom-objects#post-%2Fcrm%2Fv3%2Fobjects%2F%7Bobjecttype%7D%2Fbatch%2Fcreate).

For all the NodeJs examples, the actual line where the GET/POST request is made looks something like this:

```
const apiResponse = await hubspotClient.crm.objects.batchApi.post-/crm/v3/objects/{objectType}/batch/create(objectType, objects);
```

You can tell from a glance that this is syntatically wrong because of the `.post-` part and the slashes after it. I tried running it just to be sure and it errors out because JS think it's a regex. 

**All documentation pages for NodeJs have such similar errors.**

For my specific use case, where I wanted to create records for a custom object called Transactions, this fix worked:

```
const apiResponse = await hubspotClient.crm.objects.batchApi.create(objectType, transactions);
```

I wanted to check why, and sure enough the [BatchApi class](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/objects/apis/BatchApi.ts) has create and other methods, so the npm package is working great, it's just the documentation that's wrong.

Please fix the documentation. I had to spend a lot of time and trial-error to find this workaround.

**Comment by ksvirkou-hubspot** [comment]
Hi @siddheshranade 
For me all the NodeJs examples are correctly.
Batch create in custom objects : `const apiResponse = await hubspotClient.crm.objects.batchApi.create(objectType, BatchInputSimplePublicObjectInputForCreate);`
Maybe it was cache or deploy issue.

**Comment by siddheshranade** [comment]
@ksvirkou-hubspot You're right. I just checked those pages again and all looks good now. I did discuss this issue with colleagues yesterday to get help debugging and even they saw the same issue, so I guess you guys must've fixed it...? Either way, closing the issue, thanks.

**Comment by siddheshranade** [comment]
This error is popping up again:

![bug](https://github.com/HubSpot/hubspot-api-nodejs/assets/18247171/767f8358-c7d7-4188-bba8-7775f6f69f62)

I'm on Windows 11, Chrome v125. The above page is at https://developers.hubspot.com/docs/api/crm/crm-custom-objects.

cc @ksvirkou-hubspot

**Comment by ksvirkou-hubspot** [comment]
Looks good now...

**Comment by ksvirkou-hubspot** [comment]
It has been fixed

**Comment by siddheshranade** [comment]
Thank you @ksvirkou-hubspot.

**Comment by siddheshranade** [comment]
@ksvirkou-hubspot Showing up again:

![image](https://github.com/user-attachments/assets/8917d87a-252c-491f-9f57-a736c4c8d6ed)

Apart from the syntax error the section looks to be wrong - it says we can "Create or update a batch of objects" using an `upsert` endpoint, but no such endpoint seems to exist. I even checked the `objects/apis/BatchApi.ts` [class](https://github.com/HubSpot/hubspot-api-nodejs/blob/bfaa106af7199adbce5f766b1eb35a73f3c72499/codegen/crm/objects/apis/BatchApi.ts) and didn't find anything.

Can you let me know if it's possible to upsert custom objects?

**Comment by ksvirkou-hubspot** [comment]
The method haven't been added in the SDK yet. The method was added to API recently and we need time to add it.

**Comment by ksvirkou-hubspot** [comment]
You can use it via `hubspotClient.apiRequest()` method.

**Comment by siddheshranade** [comment]
> You can use it via hubspotClient.apiRequest() method.

@ksvirkou-hubspot Thanks, but can you explain this a bit more? Do you have an example? It would really help my use case if I had upsert ability for custom objects 🙏
