### ISSUE TITLE
Incorrect type definitions for ListSearchRequest

### ISSUE THREAD

**Issue by vitalyscrumlaunch** [HubSpot/hubspot-api-nodejs#489]
Hello
According to the [documentation](https://developers.hubspot.com/docs/api/crm/lists#search-for-a-list)
I can add the field `processingTypes: ['MANUAL', 'DYNAMIC', 'SNAPSHOT']` but `ListSearchRequest` doesn't have this field
Also there is an example how to use it [Link](https://developers.hubspot.com/beta-docs/reference/api/crm/lists#post-%2Fcrm%2Fv3%2Flists%2Fsearch) and it also has the field `processingTypes`
```ts
const hubspot = require('@hubspot/api-client');

const hubspotClient = new hubspot.Client({"accessToken":"YOUR_ACCESS_TOKEN"});

const ListSearchRequest = { listIds: ["string"], offset: 0, query: "string", count: 0, processingTypes: ["string"], additionalProperties: ["string"], sort: "string" };

try {
  const apiResponse = await hubspotClient.crm.lists.listsApi.doSearch(ListSearchRequest);
  console.log(JSON.stringify(apiResponse, null, 2));
} catch (e) {
  e.message === 'HTTP request failed'
    ? console.error(JSON.stringify(e.response, null, 2))
    : console.error(e)
}
```

ListSearchRequest
```ts
export declare class ListSearchRequest {
    'offset': number;
    'query'?: string;
    'count'?: number;
    'additionalProperties': Array<string>;
    static readonly discriminator: string | undefined;
    static readonly attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
        format: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
        format: string;
    }[];
    constructor();
}
```
and as a result I always get the empty array of the lists. When I execute this request through `node:fetch` and add the processingTypes: ['MANUAL', 'DYNAMIC', 'SNAPSHOT'] to the body it returns me all my lists.

**Comment by ksvirkou-hubspot** [comment]
Hi @vitalyscrumlaunch 
The `processingTypes` property was add to `ListSearchRequest` in [the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.1).
