### ISSUE TITLE
can we please get the access to create_or_update v3 api

### ISSUE THREAD

**Issue by GorvGoyl** [HubSpot/hubspot-api-nodejs#5]
I was integrating hubspot api and went with the shiny new v3 only to find out the basic create_or_update api is not available. :(
Any timeline when will it be available? 
Meanwhile what is the good approach? make 1st api call to check email then 2nd call based on it to create/update api?

ref: https://developers.hubspot.com/docs/methods/contacts/create_or_update

**Comment by yfaktor** [comment]
hi @JerryGoyal - thank you for your question , we will implement create_or_update in the SDK - I think in a couple of weeks. The approach is indeed to check email and then do the 2nd call. The challenge there might that search rate limit is more strict that other calls, so we will implement a back off/retry strategy for rate limit for search first, like we did for other methods

**Comment by JerryGoyal** [comment]
oh I see, curious if it is the same approach which was used in API v1 of create_or_update?

**Comment by liu578** [comment]
@yfaktor It seems like for implementation of this feature, you guys want to make two HTTP requests in  the client instead of creating an backend endpoint as version 1? Any reason for the change?

**Comment by yfaktor** [comment]
> @yfaktor It seems like for implementation of this feature, you guys want to make two HTTP requests in the client instead of creating an backend endpoint as version 1? Any reason for the change?
 hi @liu578 - sorry , I should clarify - we talked to our back end team and plan to implement an end point for this. 2 HTTP requests are only suggested as a workaround for now

**Comment by liu578** [comment]
@yfaktor sounds good, thank you.

**Comment by gamebenchjake** [comment]
Any update on this? It's been a while now...

**Comment by cristyansv** [comment]
nearly a year has passed and there is still no clear answer.

Removing a feature that was in API V1 is not a good way...

**Comment by dkonopka** [comment]
@yfaktor any news on this? Its sad that `create` endpoint is throwing an error and its not easy to continue working other scripts in application...

**Comment by dkonopka** [comment]
Any news on this? It'd be great to see it in the new API.

**Comment by robertDD11** [comment]
Any updates here? Would also love to be able to create or update batches.

**Comment by lukeramsden** [comment]
In our integration we upsert by trying to create and then handling the CONFLICT error.... what a complete mess. The backend team is either very stretched thin or wrangling with the same technical debt that causes such poor request QoS (constant 503s)!

**Comment by jdcaacbay-wp** [comment]
Still no update on this?

**Comment by kryptamine** [comment]
Are there any updates?

**Comment by joachim-pryntad** [comment]
Any updates? It's been two years now and I would really like to use this API instead of handling a failing update and then create a contact..

**Comment by e-compton** [comment]
Could really do with this feature. We have a race-condition where we do `contacts.searchApi.doSearch` to find the contact and then create it if it doesn't exist. But the doSearch API seems to update slowly and so we get "Contact already exists" errors

**Comment by beafb** [comment]
Any update on this ?

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
As long as Hubspot doesn't support the method.
We won't create the method in the SDK.
Workaround:
```javascript
async function createOrUpdateContact(properties) {
    let contact = undefined
    try {
        contact = await hubspotClient.crm.contacts.basicApi.getById(properties.email, undefined, undefined, undefined, undefined, 'email');
    } catch (error) {
        error.message === 'HTTP request failed'
        ? console.error(JSON.stringify(error.response, null, 2))
        : console.error(error)
    }

    if (contact === undefined) {
        return await hubspotClient.crm.contacts.basicApi.create({properties});
    } else {
        return await hubspotClient.crm.contacts.basicApi.update(properties.email, {properties}, 'email')
    }
}


createOrUpdateContact({
    email: 'email@example.com',
    firstname: 'New name'
})
```

**Comment by kevincolten** [comment]
@ksvirkou-hubspot This method won't account for non-primary emails, correct? Which would break if you tried to create a contact with an email that existed as a non-primary email on an existing contact.

You would have to do a search like

```js
async function createOrUpdateContact(properties) {
    let contact;
    try {
        contact = await hubspot.crm.contacts.searchApi.doSearch({
        filterGroups: [
          {
            filters: [
              {
                propertyName: "email",
                operator: "EQ",
                value: properties.email,
              },
            ],
          },
          {
            filters: [
              {
                propertyName: "hs_additional_emails",
                operator: "CONTAINS_TOKEN",
                value: properties.email,
              },
            ],
          },
        ],
        sorts: [],
        properties: [],
        limit: 1,
        after: 0
      });
    } catch (error) {
        error.message === 'HTTP request failed'
        ? console.error(JSON.stringify(error.response, null, 2))
        : console.error(error)
    }

    if (contact.results?.length) {
        return await hubspotClient.crm.contacts.basicApi.create({properties});
    } else {
        return await hubspotClient.crm.contacts.basicApi.update(contact.results[0].id, {properties})
    }
}
```
