### ISSUE TITLE
Deprecated and no longer supported warnings

### ISSUE THREAD

**Issue by sumitgoelpw** [HubSpot/hubspot-api-nodejs#51]
I just installed the package and got the following warnings.

```console
$ npm install @hubspot/api-client
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 51 packages, and audited 52 packages in 3s
```

Are there plans to update the dependencies?

**Comment by Splaktar** [comment]
It looks like they are migrating away from `request` as mentioned in https://github.com/HubSpot/hubspot-api-nodejs/issues/61.

**Comment by ksvirkou-hubspot** [comment]
Hey everyone
We have migrated from `request` to `node-fetch`
