### ISSUE TITLE
Support upsert for contact batch API

### ISSUE THREAD

**Issue by DanFaudemer** [HubSpot/hubspot-api-nodejs#514]
The [hubspot documentation](https://developers.hubspot.com/docs/api/crm/contacts) mention the ability to _Create or update a batch of contacts by unique property values_ with a nodejs example:

```typescript
  const apiResponse = await hubspotClient.crm.contacts.batchApi.upsert(BatchInputSimplePublicObjectBatchInputUpsert);
```

However the example does not work as the batch upsert is not implemeted for contacts.

Is this feature will be implemented?

Thanks :)

**Comment by ksvirkou-hubspot** [comment]
Hi @DanFaudemer 
This feature have beed implemented [in the latest version of the SDK](https://www.npmjs.com/package/@hubspot/api-client/v/12.0.0).
