### ISSUE TITLE
AccessToken Information Endpoint not working

### ISSUE THREAD

**Issue by 0x66656c6978** [HubSpot/hubspot-api-nodejs#530]
We are using the NodeJS SDK and we're using the function
hubspotClient.oauth.accessTokensApi.get
This function throws an error when we pass the access token like this:

```
hubspotClient.oauth.accessTokensApi.get(user.hubspotAccessToken)
```

The variable `user.hubspotAccessToken` is 100% valid and we use the literally same variable for all other requests when instantiating the client.

I debugged your code and the `get` function from your client is trying to make a request to the following endpoint (which looks correct)
 
This is the path I can see from the debugger.

```
'/oauth/v1/access-tokens/pat-eu1-censored-rest-of-access-token'
```
 
Please can you tell me what I can do?!

The error we get is
{"status":"error","message":"The access token must have the correct format","correlationId":"b8ec2a11-eadf-449f-956f-154978e9fca7"}

**Comment by atanasiuk-hubspot** [comment]
Hey @0x66656c6978 , from debugger logs it seems to that me you're passing not OAuth access token, but private access token (normally prefixed with "pat-"). Is it the case?

**Comment by 0x66656c6978** [comment]
Wdym you don't see a way to do that, how are we supposed to check who made these changes then?

**Comment by 0x66656c6978** [comment]
We're not gonna hardcode the application ID and our customers won't even know what their App ID is in the first place. They're supposed to simply create a private app and give us their access token so we can make requests on their behalf.
