### ISSUE TITLE
crm.lists.listsApi.getAll Fails

### ISSUE THREAD

**Issue by kevin-induro** [HubSpot/hubspot-api-nodejs#543]
Regarding the `crm.lists.listsApi.getAll` API method (presumably the implementation of the [Fetch Multiple Lists](https://developers.hubspot.com/beta-docs/reference/api/crm/lists#get-%2Fcrm%2Fv3%2Flists%2F) method - note: scroll to the method, their fragment links are broken, seems to be common with Hubspot).

The method calls for a list of numbers, but when providing that to the method, we get a response of `VALIDATION_ERROR` - `INVALID_INT_ID`. This is almost certainly because the API isn't sending the list of numbers correctly. The docs state that the ids `[1,2]` should be sent as `?listIds=1&listIds=2`.

I was able to get around it by using the `apiRequest` method, but the provided method should either not be provided or not be broken. Furthermore, I couldn't sent the values in the `qs` property of `apiRequest` because that takes a JS object, which can't have duplicate keys as the implementation requires. I ended up with this:

```
.apiRequest({
	method: 'GET',
	path: `/crm/v3/lists?listIds=${ids.join('&listIds=')}`,
});
```

**Comment by ksvirkou-hubspot** [comment]
Hi everyone,
Now the API correctly processes the format which the SDK sends and the method works correctly.
