### ISSUE TITLE
Typecheck of version 12.0.0 fails on systems with case sensitive file system

### ISSUE THREAD

**Issue by lennartfranke** [HubSpot/hubspot-api-nodejs#549]
Hi,

regarding the change in release 12.0.0:

> Renamed marketing.transactional.publicSmtpTokensApi to marketing.transactional.publicSMTPTokensApi.

Only the class names and imports were changed but not the file names. 

This causes type checking and build errors on systems with case sensitive file systems like ubuntu.

```
../node_modules/@hubspot/api-client/lib/codegen/marketing/transactional/types/PromiseAPI.d.ts(8,89): error TS2307: Cannot find module '../apis/PublicSMTPTokensApi' or its corresponding type declarations.
```

**Comment by atanasiuk-hubspot** [comment]
Hey @lennartfranke, thanks for reporting, fixed in 12.0.1 release
