### ISSUE TITLE
Consider using `axios` rather than `request`

### ISSUE THREAD

**Issue by IamBlueSlime** [HubSpot/hubspot-api-nodejs#61]
Hi,

`request` is deprecated since a long time and it's now common to use `axios`. A lot of generated boilerplate could be removed with this change.

Also, `request-promise-core` have some unhandled promises which are hanging our apps using `@hubspot/api-client`. Changing the request library will fix this. Also, the OpenAPI generator used here is capable of generating clients with `axios` so this change would not be _that_ painful.

I clearly understand that this change will cause some sort of big refactor but I think that it is more than relevant to use a well maintained library, especially if you're relying entirely on it like `@hubspot/api-client` do:

```json
  "dependencies": {
    "bluebird": "^3.7.2",
    "bottleneck": "^2.19.5",
    "lodash": "^4.17.19",
    "request": "^2.88.0"
  }
```

You'll be able to remove `bluebird`, which is nice too.

**EDIT:** to give more context on _why_ this should be done, some errors are unhandled which is not your fault but is causing some damages. For instance, while trying to edit a CRM contact with a bad id, maybe the error will be catch, maybe not causing the app to hang without being able to catch it:

```
    StatusCodeError: 404 - {"status":"error","message":"resource not found","correlationId":"xxx"}

      at new StatusCodeError (../../node_modules/request-promise-core/lib/errors.js:32:15)
      at Request.plumbing.callback (../../node_modules/request-promise-core/lib/plumbing.js:104:33)
      at Request.RP$callback [as _callback] (../../node_modules/request-promise-core/lib/plumbing.js:46:31)
      at Request.self.callback (../../node_modules/request/request.js:185:22)
      at Request.<anonymous> (../../node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (../../node_modules/request/request.js:1076:12)
```

**Comment by atanasiuk-hubspot** [comment]
Hi, @IamBlueSlime, thank you for reporting this. Our team is currently working on replacing of `request` (depending on what OpenAPIGenerator works well with)

**Comment by IamBlueSlime** [comment]
> Hi, @IamBlueSlime, thank you for reporting this. Our team is currently working on replacing of `request` (depending on what OpenAPIGenerator works well with)

That's nice to hear! Don't hesitate to reach me if you want to test some sort of prerelease :)

**Comment by IamBlueSlime** [comment]
Hi @atanasiuk-hubspot, hope you are fine.
Do you have an ETA on this? It is really blocking for us to have random errors. Do you need some help for something?
Thanks

**Comment by atanasiuk-hubspot** [comment]
Hi, @IamBlueSlime. We've prioritized the issue, but it will take some time to test the functionality since it requires updating of `OpenApiGenerator`. I'm expecting this to be ready in mid April.

**Comment by borfig** [comment]
Any progress? The `request` dependency is problematic right now:
```
$ npm audit 
                                                                                
                       === npm audit security report ===                        
                                                                                
                                                                                
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  Moderate        json-schema is vulnerable to Prototype Pollution              
                                                                                
  Package         json-schema                                                   
                                                                                
  Patched in      >=0.4.0                                                       
                                                                                
  Dependency of   @hubspot/api-client                                           
                                                                                
  Path            @hubspot/api-client > request > http-signature > jsprim >     
                  json-schema                                                   
                                                                                
  More info       https://github.com/advisories/GHSA-896r-f27r-55mw             
                                                                                
found 1 moderate severity vulnerability in 507 scanned packages
  1 vulnerability requires manual review. See the full report for details.```

**Comment by apeiniger** [comment]
Having the same problem. Github Dependabot is now throwing security warnings because of this outdated dependency.

**Comment by ksvirkou-hubspot** [comment]
Hi Everyone 
We have problems with OpenAPI Generator
We are working on it

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
we have rewrited SDK (now it is using fetch)
