### ISSUE TITLE
Invalid example of AssociationsApi

### ISSUE THREAD

**Issue by Splaktar** [HubSpot/hubspot-api-nodejs#62]
In the README.md, there is this example code:
```ts
await hubspotClient.crm.companies.associationsApi.create(
    createCompanyResponse.body.id,
    'contacts',
    createContactResponse.body.id,
)
```
But this doesn't build:
```ts
src/index.ts:62:87 - error TS2554: Expected 4-6 arguments, but got 3.

 62         const associationResponse = await hubspotClient.crm.companies.associationsApi.create(
                                                                                          ~~~~~~~
 63           createCompanyResponse.body.id,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 65           createContactResponse.body.id,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 66         );
    ~~~~~~~~~

  node_modules/@hubspot/api-client/lib/codegen/crm/companies/api/associationsApi.d.ts:66:73
    66     create(companyId: string, toObjectType: string, toObjectId: string, associationType: string, paginateAssociations?: boolean, options?: {
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'associationType' was not provided.
```

This JSDoc is really not helpful 😦 
```js
    /**
     *
     * @summary Associate a company with another object
     * @param companyId
     * @param toObjectType
     * @param toObjectId
     * @param associationType
     * @param paginateAssociations
     */
```
I assume that `toObjectType` can be `'contacts'` based on the sample code, but what other values are possible?

What are the valid values of `associationType`? In https://developers.hubspot.com/docs/api/crm/associations, I see only one type `"contact_to_company"`. Is there also a `"company_to_contact"` type? Where can I find documentation of the other types?

Is there an OpenAPI spec published somewhere with more details about this API?

**Comment by RobPando** [comment]
@Splaktar I was wondering about this too yesterday. The example is indeed missing a 4th required param. To answer your question, yes, you can add all the kinds of types combination their is, I needed for `tickets` so I did `contact_to_ticket` and that worked perfect.

**Comment by atanasiuk-hubspot** [comment]
Hi, @Splaktar, thanks for reporting this!

> Where can I find documentation of the other types?

Not yet available for new version of API, but can be found in the [old](https://legacydocs.hubspot.com/docs/methods/crm-associations/crm-associations-overview) one.
