### ISSUE TITLE
Model files generated by OpenAPI generator

### ISSUE THREAD

**Issue by tom-haines** [HubSpot/hubspot-api-nodejs#7]
It would be great to make the OpenAPI files used to generate these models available to customer, for example for usage in Java or Rust.

https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/contacts/model/associatedId.ts

Here you can see OpenAPI (or swagger) source file has been used, but not saved into the repo.
```
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
```

Can a copy be made available on as-id basis?

**Comment by yfaktor** [comment]
we had an internal discussion on this and agreed that the team that produces this JSON will be in the best position to make it available - probably through a dedicated end point. Please stay tuned for more on this

**Comment by tom-haines** [comment]
That's great news, thanks @yfaktor.  

I realise that one of the strengths of your v3 API is that it supports dynamic properties without being cumbersome to construct (i.e. it does not impose painful / artificial distinctions between custom properties versus default properties).  I think simply an OpenAPI spec of the primary objects defined in your [ERD model](https://developers.hubspot.com/docs/crm-integration-guide/overview) would be enough to cut singificant boilerplate code (an object schema that does not contain the complete endpoint definitions for example is still very useful).

We'd be happy to beta test / give feedback on it in our environment should opportunity present.  We maintain an [api spec](https://github.com/wisetime-io/connect-api-spec) for both client/server and have worked with OpenAPI specs on a number of fronts (though appreciate our [use case](https://wisetime.com/docs/connect/) is less complex).  

We have a few ideas about how one might support the dynamic aspects from a java library.  Once we have the json in hand, we'll push our java client to a public repo if it would help others.

**Comment by wkf** [comment]
Hello @yfaktor, has the JSON spec been made available via an endpoint yet? Thank you!

**Comment by ksvirkou-hubspot** [comment]
Hi everyone.
You can find a swagger file on a dock's page.
For example [CRM Contacts](https://developers.hubspot.com/docs/api/crm/contacts):
Open [dock's page](https://developers.hubspot.com/docs/api/crm/contacts).
Press F12 -> Network -> Fetch/XHR -> looking for [the swagger file](https://app.hubspot.com/api/api-catalog-public/v1/apis/crm/v3/contacts)
<img width="244" alt="Снимок экрана 2023-04-29 в 16 29 16" src="https://user-images.githubusercontent.com/57258237/235305732-cf3d737c-37b3-47f6-8a17-e46cbc8cf127.png">
List of swagger file included to the SDK:
[oauth](https://api.hubapi.com/api/api-catalog-public/v1/apis/auth/v1/oauth)
[automation.actions](https://api.hubapi.com/api/api-catalog-public/v1/apis/automation/v4/actions)
[cms.auditLogs](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/audit-logs)
[cms.blogs.authors](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/blogs/authors)
[cms.blogs. blogPosts](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/blogs/blog-posts)
[cms.blogs.tags](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/blogs/tags)
[cms.hubdb](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/hubdb)
[cms.domains](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/domains)
[cms.performance](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/performance)
[cms.siteSearch](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/site-search)
[cms.sourceCode](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/source-code)
[cms.urlRedirects](https://api.hubapi.com/api/api-catalog-public/v1/apis/cms/v3/url-redirects)
[conversations.visitorIdentification](https://api.hubapi.com/api/api-catalog-public/v1/apis/conversations/v3/visitor-identification)
[communicationPreferences](https://api.hubapi.com/api/api-catalog-public/v1/apis/communication-preferences/v3)
[crm.associations](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/associations)
[crm.associations.v4](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v4/associations)
[crm.companies](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/companies)
[crm.contacts](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/contacts)
[crm.deals](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/deals)
[crm.imports](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/imports)
[crm.extensions.accounting](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/extensions/accounting)
[crm.extensions.calling](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/extensions/calling)
[crm.extensions.cards](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/extensions/cards)
[crm.extensions.videoconferencing](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/extensions/videoconferencing)
[crm.lineItems](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/line_items)
[crm.objects](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects)
[crm.objects.feedbackSubmissions](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/feedback_submissions)
[crm.objects.calls](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/calls)
[crm.objects.communications](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/communications)
[crm.objects.emails](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/emails)
[crm.objects.meetings](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/meetings)
[crm.objects.notes](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/notes)
[crm.objects.postalMail](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/postal_mail)
[crm.objects.tasks](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/objects/tasks)
[crm.owners](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/owners)
[crm.pipelines](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/pipelines)
[crm.products](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/products)
[crm.properties](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/properties)
[crm.quotes](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/quotes)
[crm.tickets](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/tickets)
[crm.timeline](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/timeline)
[crm.schemas](https://api.hubapi.com/api/api-catalog-public/v1/apis/crm/v3/schemas)
[events](https://api.hubapi.com/api/api-catalog-public/v1/apis/events/v3/events)
[files](https://api.hubapi.com/api/api-catalog-public/v1/apis/files/v3/files)
[marketing.events](https://api.hubapi.com/api/api-catalog-public/v1/apis/marketing/v3/marketing-events-beta)
[marketing.transactional](https://api.hubapi.com/api/api-catalog-public/v1/apis/marketing/v3/transactional)
[settings.users](https://api.hubapi.com/api/api-catalog-public/v1/apis/settings/v3/users)
[webhooks](https://api.hubapi.com/api/api-catalog-public/v1/apis/webhooks/v3)
Feel free to reopen if any questions.
