### ISSUE TITLE
tickets/api/basicApi.ts#L183 - Always TRUE

### ISSUE THREAD

**Issue by Loop-Donsky** [HubSpot/hubspot-api-nodejs#70]
https://github.com/HubSpot/hubspot-api-nodejs/blob/302786dbb6d75aa6f127f18740c3218688e9cf36/codegen/crm/tickets/api/basicApi.ts#L183

Should probably just...
```
    localVarHeaderParams.Accept = 'application/json'
```
... to save some cycles.

**Comment by ksvirkou-hubspot** [comment]
Hi @Loop-Donsky .
It is codegen and we can't change it.
