### ISSUE TITLE
hubDbTableV3 model doesn't include foreignKey attributes

### ISSUE THREAD

**Issue by kieranja** [HubSpot/hubspot-api-nodejs#72]
https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/cms/hubdb/model/hubDbTableV3.ts

Is missing foreignTableId and foreignColumnId.

**Comment by ksvirkou-hubspot** [comment]
Hi @kieranja 
it will be fixed in the following version

**Comment by ksvirkou-hubspot** [comment]
The fields were added in version 4.0.0 but [in file column.ts](https://github.com/HubSpot/hubspot-api-nodejs/blob/4.0.0/codegen/cms/hubdb/model/column.ts#L37).
