### ISSUE TITLE
SDK documentation of available methods and usage

### ISSUE THREAD

**Issue by javonclarke** [HubSpot/hubspot-api-nodejs#73]
It'd be nice to have documentation on the methods available as opposed to reading through the code implementation.

**Comment by holub008** [comment]
https://developers.hubspot.com/docs/api/overview enumerates API endpoints (e.g. [Contacts API](https://developers.hubspot.com/docs/api/crm/contacts)), which have Node examples for this lib under the Endpoints tab. Granted, they still seem poorly documented and several of the examples I pulled were out of date or incorrect.

**Comment by ksvirkou-hubspot** [comment]
[Link to API documentation ](https://developers.hubspot.com/docs/api/overview)
There are node examples for the SDK under the Endpoints tab.
We have refreshed it and most of examples are workable now.
