### ISSUE TITLE
❓SearchAPI: sorts param as Array<string> vs. Array<object> in documentation?

### ISSUE THREAD

**Issue by luskin** [HubSpot/hubspot-api-nodejs#9]
According to the documentation found [here](https://developers.hubspot.com/docs/api/crm/search) the `sorts` param in the `searchApi` should be an object array, not a string array, i.e.: 

```typescript
"sorts": [
      {
        "propertyName": "createdate",
        "direction": "DESCENDING"
      }
    ]
```

In the [typing](https://github.com/HubSpot/hubspot-api-nodejs/blob/master/codegen/crm/deals/model/publicObjectSearchRequest.ts), however, we see that `sorts` is an `Array<string>`:

```typescript
export declare class PublicObjectSearchRequest {
    'filterGroups': Array<FilterGroup>;
    'sorts': Array<string>;
    'query'?: string;
    'properties': Array<string>;
    'limit': number;
    'after': number;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
```

Since the README is quite sparse on this, I was hoping to get some clarity on how the sorting should be implemented. Thanks and keep up the good work on this SDK, it's super useful!

**Comment by AProts** [comment]
Hi @luskin ,

Thanks for your question and sorry for so delayed response. 

Despite 'sorts' is an array, however, currently, CRM objects Search API supports only one sort parameter. If more than one search sort parameter provided, a similar error would be received: 

```
{
    "status": "error",
    "message": "too many sorts (count: 2, max allowed: 1)",
    "correlationId": "62138cf8-57cb-41d1-8982-2f4c941ce72e",
    "category": "VALIDATION_ERROR"
}
```

In JS for 'sorts' it's possible to set as:

1. [<propertyName>] - returned results will be sorted by provided property name in 'ASCENDING' order. e.g: ['hs_object_id']
2. [<stringified sort object>] - returned results will be sorted by provided property name and sort direction. e.g: [JSON.stringify({ propertyName: 'hs_object_id', direction: 'ASCENDING' })] or [JSON.stringify({ propertyName: 'hs_object_id', direction: 'DESCENDING' })]
3. [<sort object>] - returned results will be sorted by provided property name and sort direction. e.g: [{ propertyName: 'hs_object_id', direction: 'ASCENDING' }] or [{ propertyName: 'hs_object_id', direction: 'DESCENDING' }]

In TS works only the first two options.

We will add sort examples to readme in the upcoming release.

Kind Regards,
Andrii

**Comment by AProts** [comment]
updated README in 2.1.1

**Comment by amouly** [comment]
This doesn't work with the Companies Search API.

I've tested sending an JSON stringify object and still not being applied.

Also tested on Postman sending:

```
{
  "filterGroups": [],
  "limit": 100,
  "after": 300,
  "properties": [
    "billing_status"
  ],
  "sorts": [
    "{\"propertyName\": \"hs_lastmodifieddate\",\"direction\": \"DESCENDING\"}"
  ]
}
```

And the sort value is not making any effect.

**Comment by DosCervezas** [comment]
Also does not work in the SDK objects.SearchApi

`client.crm.objects.searchApi.doSearch`

**Comment by TomerKidronCTRL** [comment]
@AProts 
Why was this issue closed? The given solution still does not work.
The workaround I am using for the meantime is to search through `hubspotClient.apiRequest`, which does not return a typed result but at least works with sort.

**Comment by dellMarco** [comment]
> 1. [< propertyName >] - returned results will be sorted by provided property name in 'ASCENDING' order. e.g: ['hs_object_id']
> 2. [< stringified sort object >] - returned results will be sorted by provided property name and sort direction. e.g: [JSON.stringify({ propertyName: 'hs_object_id', direction: 'ASCENDING' })] or [JSON.stringify({ propertyName: 'hs_object_id', direction: 'DESCENDING' })]
> 3. [< sort object >] - returned results will be sorted by provided property name and sort direction. e.g: [{ propertyName: 'hs_object_id', direction: 'ASCENDING' }] or [{ propertyName: 'hs_object_id', direction: 'DESCENDING' }]
> 
> In TS works only the first two options.

Option 1 and 2 don't work for me in TS, workaround was to set the search Object as any and use Option 3:

```
const sort = {
    propertyName: 'createdate',
    direction: 'ASCENDING',
  } as any
```

**Comment by huesoskywalker** [comment]
My solution was to modify the class PublicObjectSearchRequest like this:
import { FilterGroup } from '../models/FilterGroup';
export declare class PublicObjectSearchRequest {
    'filterGroups': Array<FilterGroup>;
    'sorts': Array<{ propertyName: string, direction: string }>;
    'query'?: string;
    'properties': Array<string>;
    'limit': number;
    'after': number;
    static readonly discriminator: string | undefined;
    static readonly attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
        format: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
        format: string;
    }[];
    constructor();
}

Change -> sorts: Array<string> to -> sorts: Array<{ propertyName: string, direction: string }>
