### ISSUE TITLE
templatesApi is not getting developerApiKey from client

### ISSUE THREAD

**Issue by pploneczka** [HubSpot/hubspot-api-nodejs#90]
If client is initialised with developerApiKey and then crm.timeline.templatesApi is selected to perform request developerApiKey is missing in that request resulting in error "Any of the listed authentication credentials are missing" and status 401. 

Only way to get it to work that I found it to explicitly call setApiKey on templatesApi.

**Comment by ksvirkou-hubspot** [comment]
Hi @pploneczka .
Thank you for reporting the issue.
It was fixed in [6.0.1](https://github.com/HubSpot/hubspot-api-nodejs/tree/6.0.1).
