### ISSUE TITLE
How do I add an existing contact to a ticket?

### ISSUE THREAD

**Issue by ramseth001** [HubSpot/hubspot-api-nodejs#92]
I am trying to add (associate) an existing contact while creating a ticket. I tried to add "hs_object_id" to the properties. But I am getting VALIDATION ERROR. Kindly assist me with this issue

**Comment by ksvirkou-hubspot** [comment]
@ramseth001 
for Associations exists 
```
hubspotClient.crm.tickets.associationsApi.create
```
