### ISSUE TITLE
hubSpotClient.crm.contacts.basicApi.getByEmail() missing

### ISSUE THREAD

**Issue by HuckleberryCarignan** [HubSpot/hubspot-api-nodejs#96]
The method to get a contact by way of email is not present (or at least I can't find it).

**Comment by ksvirkou-hubspot** [comment]
our SDK is one to one with API 
This method doesn’t not exist in API
@HuckleberryCarignan

**Comment by ksvirkou-hubspot** [comment]
https://github.com/HubSpot/hubspot-api-nodejs/issues/99

**Comment by dreadjr** [comment]
@ksvirkou-hubspot It is exposed via `idProperty` for the `GET` on contact
