### ISSUE TITLE
update_contact-by-email

### ISSUE THREAD

**Issue by AlexHodovas** [HubSpot/hubspot-api-nodejs#99]
Hello 
@ksvirkou-hubspot 

Can you help please?
Where is this method ?

[docs/methods/contacts/update_contact-by-email](https://legacydocs.hubspot.com/docs/methods/contacts/update_contact-by-email)

**Comment by atanasiuk-hubspot** [comment]
Hi, @AlexHodovas, the url above links to legacy docs, which is not supported by this SDK.

Please check a [new](https://developers.hubspot.com/docs/api/overview) version of API.

**Comment by ksvirkou-hubspot** [comment]
hi @nmazidi  
Could you check [the latest version](https://www.npmjs.com/package/@hubspot/api-client/v/5.0.0) ?

**Comment by nmazidi** [comment]
Hi @ksvirkou-hubspot 

Looks like the latest version does have it now, thanks! :)
